odigos-io/odigos

autoscaler/controllers/datacollection/daemonset.go, instrumentor/controllers/instrumentedapplication_controller.go, ui/vendors/index.tsx
This PR fixes the following:
- Fix a bug where logs won't be discovered for Docker CRI.
- Fix OutOfPods error when working with EKS
=> fix logs sending for docker CRI

ui/components/CurrentDestsGrid.tsx
Typo: `%s/cofigured/configured`
=> [MINOR] Fix minor typo

.github/workflows/main.yml, Dockerfile, langDetector/Dockerfile
This PR is the first part of making Odigos support ARM processrors.
I am currently testing it on Apple Silicon. 
This PR changes the github workflow to build multi architecture images.
=> ARM Support: build multi arch images

ui/components/EditAppCard.tsx, ui/pages/api/source/[namespace]/[kind]/[name].ts, ui/pages/source/[namespace]/[kind]/[name].tsx
This PR fixes a bug in the UI where the application edit page caused 500 internal error.
=> bug fix: enable source instrumentation via ui

autoscaler/controllers/collectorsgroup_controller.go, autoscaler/controllers/datacollection/daemonset.go, autoscaler/controllers/datacollection/root.go, autoscaler/controllers/destination_controller.go, autoscaler/controllers/gateway/deployment.go, autoscaler/controllers/gateway/root.go, autoscaler/controllers/instrumentedapplication_controller.go, autoscaler/main.go
This PR propagate the `imagePullSecrets` value from the helm chart to the collectors created by autoscaler (data collection & gateway collectors).
=> Propagate ImagePullSecrets to collectors

langDetector/inspectors/golang.go, langDetector/inspectors/java.go
This PR improves the way Odigos detect Java and Go processes.
=> Improve detection of Go and Java

autoscaler/controllers/gateway/config/middleware.go
This PR fixes an import error at the `middleware.go` file
=> fix import error

.github/workflows/build.yaml
This PR adds a compilation check for every pull request.
=> Add compilation check

ui/pages/dest/new/[destname].tsx
https://user-images.githubusercontent.com/44473671/232625612-18a8b075-29cf-40d2-800e-cf6eb29b0f9c.mp4
=> Validate destinations URLs in frontend before saving #73

frontend/endpoints/destinations.go
fixes:
1. if destination failed to create - revert the secret update
2. use "fields" instead of "data" in the payload
3. when no destinations are present, return empty array instead of null
=> fix: issues in destinations api

frontend/webapp/containers/overview/overview/overview.tsx, frontend/webapp/containers/setup/connection/connection.section.tsx, frontend/webapp/containers/setup/destination/destination.section.tsx, frontend/webapp/containers/setup/setup.section/setup.section.tsx, frontend/webapp/containers/setup/sources/sources.section.tsx, frontend/webapp/services/destinations.tsx, frontend/webapp/services/index.tsx, frontend/webapp/services/sources.tsx
=> restructure service files

frontend/webapp/app/overview/sources/page.tsx, frontend/webapp/containers/overview/index.tsx, frontend/webapp/containers/overview/sources/sources.styled.tsx, frontend/webapp/containers/overview/sources/sources.tsx
boiler plate for the sources overview page
=> Task 149 sources container

cli/pkg/confirm/confirm.go
=> Recognize crlf and lf as yes in Ask method

.github/dependabot.yml
=> grouped dependencies updates for kubernetes and opentelemetry

autoscaler/controllers/gateway/config/elasticapm.go, autoscaler/controllers/gateway/config/root.go, common/dests.go, destinations/data/elasticapm.yaml, destinations/logos/elasticapm.svg
Resolve #528 
Tested on: 
- self hosted APM server 8.9.2
- managed Elastic Cloud deployment 8.10.1
=> elastic apm destination added and configured

destinations/data/logzio.yaml
#487 
Created a dropdown similar to what was done in datadog's case.
=> Destination: logz.io region field dropdown

frontend/endpoints/namespaces.go
issue: #542 
removed logs and code refactoring
=> fix : Removed unnecessary logs

.goreleaser.yaml, frontend/main.go, frontend/version/version.go
- Inject version info to `odigos-ui` binary
- Add flag to print version in `odigos-ui` binary
Fixed #551 #552
=> Inject ui version and add option to print it

CODE_OF_CONDUCT.md, README.md
Added Contributors section in readme.md file!
=> Fixed #602 Updated README.md

README.md
Making the hacktoberfest section Appealing  by adding emojis and rephrasing text.
Before:
After :
=> [Enhancement] :Making the hacktoberfest section Appealing 

docs/telemetry-types.mdx
Added supported libraries for every language Icon Cards in telemetry-types.mdx for more better and clean look.
- before:
- After:
=> Added supported libraries for every language Icon Cards in telemetry-types.mdx

CONTRIBUTING.md
=> Removing dead links from CONTRIBUTING.md

LICENSE
https://github.com/circlefin/circle-ecosystem/pull/73
I saw this pull request of this project. They update the placeholder with the corresponding information. In the LICENSE file.
=> Updated placeholder with the corresponding information

CONTRIBUTING.md
Synced fork with recent pull request #672 and then added the How to Develop Odigos Locally section
=> Update CONTRIBUTING.md; Added How to Develop Odigos Locally Section

CONTRIBUTING.md
Fix Typo and added suitable words in CONTRIBUTING.md File
=> Fix Typo in CONTRIBUTING.md File

docs/mint.json
@alonkeyval Please review my pull request and merge it.
=> Changed twitter to X 

autoscaler/controllers/gateway/config/newrelic.go, destinations/data/newrelic.yaml
=> Add dropdown for seleecting new relic endpoint

cli/cmd/version.go
Like other comands without flags, the comments are not necessary
=> Remove comments

.github/workflows/e2e/bats/utilities.bash, .github/workflows/e2e/bats/verify.bats, autoscaler/controllers/gateway/config/root.go, autoscaler/controllers/gateway/deployment.go
=> Add odigos.version resource attribute

CONTRIBUTING.md, cli/cmd/upgrade.go, docs/pipeline/sources/source-configuration.mdx, docs/pipeline/sources/troubleshooting.mdx, frontend/main.go
- **docs: missing "set"**
- **docs: capitalize "UI" and "Odigos" where appropriate**
- **docs: make the subject consistent "you" (instead of the "user" in the first sentence) in troubleshooting.mdx like everywhere else**
Promised to review #1081, but got to it only now. Addressed some of the tiny inconsistencies I noticed while reviewing. Feel free to merge or close this.
=> docs: review #1081 and address some of the nits and inconsistencies

docs/quickstart/introduction.mdx
=> Adds the missing commands in quickstart introduction page

CONTRIBUTING.md
Fixes #1098
https://docs.odigos.io/overview -> https://docs.odigos.io/quickstart/introduction
=> Fixes the inaccurate link in CONTRIBUTING.md

.github/workflows/sync-logos-s3-bucket.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
=> ci: sync logos only if they were changed

api/config/crd/bases/odigos.io_odigosconfigurations.yaml, api/generated/odigos/applyconfiguration/odigos/v1alpha1/odigosconfigurationspec.go, api/odigos/v1alpha1/odigosconfig_types.go, autoscaler/controllers/gateway/deployment.go, cli/cmd/install.go, cli/cmd/resources/crds/configuration.go, cli/cmd/resources/odiglet.go, docs/cli/odigos_install.mdx, odiglet/pkg/instrumentation/fs/agents.go
address https://github.com/keyval-dev/odigos/issues/1128
=> install odigos in openshift

.github/workflows/check-links.yml, README.md
Fix broken link in README and add GH for validating links.
=> Fix broken link in README and add links check to CI

frontend/webapp/components/setup/connection/create.connection.form/create.connection.form.tsx, frontend/webapp/containers/main/instrumentation-rules/choose-rule/index.tsx
Just 2 minor changes to texts to make them a bit better
=> fix: better texts in ui

docs/mint.json
addresses: https://github.com/odigos-io/odigos/runs/31692785270
=> fix: mint json syntax

k8sutils/pkg/describe/odigos.go, k8sutils/pkg/describe/odigos/resources.go, k8sutils/pkg/describe/source.go, k8sutils/pkg/describe/source/resources.go, k8sutils/pkg/describe/source/source.go
This is just improving the structure of the code, to prepare it for follow-up refactors while having small - reviewable PRs
=> refactor: extract resource collection for odigos describe into separate package

.gitignore
small change, not sure if this was left out intentionally or not
=> Add go.work to gitignore

autoscaler/controllers/collectorsgroup_controller.go, autoscaler/controllers/datacollectiondaemonset_controller.go, autoscaler/controllers/destination_controller.go, autoscaler/controllers/gatewaydeployment_controller.go, autoscaler/controllers/instrumentedapplication_controller.go, autoscaler/controllers/odigosconfig_controller.go, instrumentor/controllers/deleteinstrumentedapplication/daemonset_controller.go, instrumentor/controllers/deleteinstrumentedapplication/deployment_controller.go, instrumentor/controllers/deleteinstrumentedapplication/instrumentedapplication_controller.go, instrumentor/controllers/deleteinstrumentedapplication/namespace_controller.go, instrumentor/controllers/deleteinstrumentedapplication/statefulset_controller.go, instrumentor/controllers/instrumentationdevice/instrumentedapplication_controller.go, scheduler/controllers/destination_controller.go
This PR is a general housekeeping, removing some auto-generated comments with trivial or non-up-to-date info, that does not give any value to our code base.
=> chore: cleanup irrelevant comments

common/envOverwrite/overwriter.go, k8sutils/pkg/envoverwrite/origenv.go
=> Revert "fix: update original value in annotation when overriden by user"

instrumentor/controllers/instrumentationdevice/common.go, instrumentor/controllers/instrumentationdevice/instrumentedapplication_controller.go, instrumentor/controllers/instrumentationdevice/manager.go, instrumentor/instrumentation/instrumentation.go
=> Revert "fix: use instrumentation config with generation to inject env vars"

.github/workflows/e2e.yaml
Missed this when adding the test. Now it will actually run
=> Enable source e2e test scenario

k8sutils/pkg/describe/source/analyze.go
Syncing main with feature branch to resolve conflicts and reduce amount of changed files.
=> Sync main into feature/source-crd

.github/workflows/publish-modules-artifactregistry.yml
* Add manual dispatch to re-run
* Use gcp auth @ v2
* Add contents+token permissions
=> fix Artifact Registry release workflow

.github/workflows/publish-modules-artifactregistry.yml
https://github.com/google-github-actions/auth?tab=readme-ov-file#outputs
=> Add access_token to artifact_registry workflow

cli/cmd/root.go, cli/go.mod, docs/cli/odigos.mdx, docs/cli/odigos_cloud.mdx, docs/cli/odigos_cloud_login.mdx, docs/cli/odigos_cloud_logout.mdx, docs/cli/odigos_cloud_update.mdx, docs/cli/odigos_config.mdx, docs/cli/odigos_config_set.mdx, docs/cli/odigos_describe.mdx, docs/cli/odigos_describe_source.mdx, docs/cli/odigos_describe_source_daemonset.mdx, docs/cli/odigos_describe_source_deployment.mdx, docs/cli/odigos_describe_source_statefulset.mdx, docs/cli/odigos_diagnose.mdx, docs/cli/odigos_install.mdx, docs/cli/odigos_pro.mdx, docs/cli/odigos_profile.mdx, docs/cli/odigos_profile_add.mdx, docs/cli/odigos_profile_remove.mdx, docs/cli/odigos_sources.mdx, docs/cli/odigos_sources_create.mdx, docs/cli/odigos_sources_delete.mdx, docs/cli/odigos_sources_status.mdx, docs/cli/odigos_sources_update.mdx, docs/cli/odigos_ui.mdx, docs/cli/odigos_uninstall.mdx, docs/cli/odigos_upgrade.mdx, docs/cli/odigos_version.mdx
This flag will log every interaction with Kubernetes API server
=> Add -v flag to CLI

DEVELOPMENT.md
This just adds some notes on Go workspaces and examples for using them
=> Add development notes on using Go workspaces

.github/actions/build/cli/action.yml, .github/actions/nightly/report/action.yml, .github/workflows/build-dev-images.yml, .github/workflows/chaos-tests.yml, .github/workflows/cross-cloud-tests.yaml, .github/workflows/nightly.yml, .github/workflows/run-chaos-tests.yml, .github/workflows/run-cross-cloud-tests.yml, Makefile, tests/chaos/common/install_chaos_mesh.sh, tests/chaos/network-latency/leader-election/chainsaw-test.yaml, tests/e2e/helm-chart/chainsaw-test.yaml
Created a single nighty workflow.
Moved image creation logic out of cloud provider tests
Added a chaos test
=> GitHub workflows grooming

profiles/manifests/category-attributes.yaml
Changing the category attributes for elasticsearch rest client
=> chore: adjust category attributes for java elastic rest

collector/Makefile, collector/processors/odigossamplingprocessor/config.go, collector/processors/odigossamplingprocessor/factory.go, collector/processors/odigossamplingprocessor/internal/sampling/error.go, collector/processors/odigossamplingprocessor/internal/sampling/error_test.go, collector/processors/odigossamplingprocessor/internal/sampling/latency.go, collector/processors/odigossamplingprocessor/internal/sampling/latency_test.go, collector/processors/odigossamplingprocessor/internal/sampling/sampling.go, collector/processors/odigossamplingprocessor/internal/sampling/testutil/tracefactory.go, collector/processors/odigossamplingprocessor/processor.go, collector/processors/odigossamplingprocessor/rule_engine.go, collector/processors/odigossamplingprocessor/rule_engine_test.go
Refactor `odigossamplingprocessor` sampling logic.
=> Odigos sampling processor refactor

odiglet/pkg/instrumentation/fs/agents.go
User reported Odiglet init containers failing on OpenShift with the following:
```
{"level":"error","ts":1742824305.449013,"caller":"fs/agents.go:159","msg":"Error running semanage command","error":"exit status 1","stacktrace":"[github.com/odigos-io/odigos/odiglet/pkg/instrumentation/fs.ApplyOpenShiftSELinuxSettings\n\t/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/pkg/instrumentation/fs/agents.go:159\ngithub.com/odigos-io/odigos/odiglet.OdigletInitPhase\n\t/go/pkg/mod/github.com/odigos-io/odigos/odiglet@v1.0.162/odiglet.go:203\nmain.main\n\t/go/src/github.com/odigos-io/odigos-enterprise/odiglet/cmd/enterprise/main.go:42\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272](http://github.com/odigos-io/odigos/odiglet/pkg/instrumentation/fs.ApplyOpenShiftSELinuxSettings%5Cn%5Ct/g …
```
=> odiglet: Handle re-running semanage on openshift

tests-infrastructure/terraform/eks/main.tf, tests/e2e/README.md, tests/e2e/helm-chart/queries/span-attributes.yaml, tests/e2e/multi-apps/queries/span-attributes.yaml
This PR fixes the nightly tests
=> chore: adjust tf to support new db

instrumentor/internal/webhook_env_injector/webhook_env_injector.go
=> chore: change set env order

agents/python/setup.py
Version bump to odigos-opentelemetry-python
=> Use new version of odigos-opentelemetry-python

agents/python/setup.py
Version bump odigos-opentelemetry-python
=> Version bump odigos-opentelemetry-python

autoscaler/controllers/actions/k8sattributesresolver_controller.go
The k8sattributes processor is designed for our spans, where spans generated from odigos always contains `k8s.deployment.name`, `k8s.daemoneset.name` or `k8s.statefulset.name`.
However, for logs collected with `filelog` receiver, those attributes are missing and are not enhanced by the processor.
This PR checks if one of the k8sattributes actions is configured to collect logs, and add those attributes by default if they are.
This change requires to resolve deployments etc in node collector. we need to do it anyway as logs are not very useful without this info of what workload originated it. the `k8sattributes` processor uses informer and caches data internally and is a contrib processor which we already use and recommend.
Uses which collect logs and have the `k8sattributes` action enabled …
=> fix: resolve also workload names in k8s attributes processor

cli/cmd/profile.go
`odigos profile` currently prints the name of the configured profiles (those that user added to odigos config via cli or helm or manually setting the cm).
However, the profiles which are used from the api token are not printed.
This PR makes it so that they are also printed in the command.
Example output (new):
```
Profiles set in config:
- size_l
- copy-scope
Profiles from odigos api token:
- kratos
Effective profiles:
- size_l
- copy-scope
- kratos
- db-payload-collection
- semconv
- category-attributes
- copy-scope
- hostname-as-podname
- code-attributes
- query-operation-detector
- small-batches
- size_m
- allow_concurrent_agents
- mount-method-k8s-host-path
```
Output (old):
```
Currently applied profiles: [size_l copy-scope]
```
Manually running the command (w/o token profiles, …
=> feat: print api token and effective profiles in cli

operator/Makefile, operator/bundle/manifests/odigos-operator-odigos-version-m5529f26df_v1_configmap.yaml, operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/manifests/bases/odigos-operator.clusterserviceversion.yaml
=> Update operator to v1.0.183

odiglet/Dockerfile, odiglet/Dockerfile.rhel, odiglet/debug.Dockerfile
This version supports `opcache.preload_user` for `www-data` users
=> feat: bump PHP agents to v0.1.18

.github/workflows/nightly.yml, tests/common/queries/span-attributes-reported.yaml
=> Replace nightly multi apps with source

.github/workflows/check-links.yml
Change the cache access for a repo scope
=> Change cache access

operator/Makefile, operator/bundle/manifests/odigos-operator-odigos-version-db9k7g76mc_v1_configmap.yaml, operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml, operator/config/manager/kustomization.yaml, operator/config/manager/manager.yaml, operator/config/manifests/bases/odigos-operator.clusterserviceversion.yaml
=> operator: Update to v1.0.185

agents/python/setup.py
=> Version bump python agent

tests/chaos/network-latency/leader-election/chainsaw-test.yaml
=> Fix race condition in k8s resources

docs/reo.js
Include a JS script to gather analytics on Odigos docs usage
=> add analytics to docs

frontend/webapp/app/layout.tsx, frontend/webapp/public/manifest.json
This PR fixes the image "type" and "sizes" values for the UI favicon.
=> fix: UI favicon

autoscaler/controllers/actions/sampling/spanattributesampler.go, collector/processors/odigossamplingprocessor/internal/sampling/spanattribute.go
=> Use flat structure to handle sampler config

instrumentor/controllers/agentenabled/sync.go
#2971 introduced a change that after initial instrumentation, the agentenabled controller in instrumentor will requeue for 10 seconds to check for crashloop backoff.
This works well for 1 workload, but when called from `reconcileAll`, this change makes it so that we now break early from the loop before handling all workload, leading to agents being started one by one with 10 second intervals.
This PR makes it so that we always process all workloads, and aggregate the results from all calls to fix this issue
=> fix(instrumentor): aggregate result of reconcile all instead of breaking

cli/cmd/pro.go
`odigos pro update-offsets` updates the offsets file, but instrumentations that already exist won't get that update. This is a quick fix to make the cli command restart the odiglet which should re-trigger the instrumentations to consume the latest offsets
=> update-offsets: restart odiglet to apply new Go offsets

frontend/graph/generated.go, frontend/graph/schema.graphqls, frontend/graph/schema.resolvers.go, frontend/services/sources.go, frontend/services/utils.go, frontend/webapp/app/(overview)/overview/page.tsx, frontend/webapp/app/(overview)/sources/page.tsx, frontend/webapp/components/lib-imports/overview-modals-and-drawers.tsx, frontend/webapp/graphql/mutations/source.ts, frontend/webapp/hooks/sources/index.ts, frontend/webapp/hooks/sources/useWorkloadUtils.ts, frontend/webapp/package.json, frontend/webapp/yarn.lock
This PR adds the option to rollout restart workloads from the UI.
Depends on: https://github.com/odigos-io/ui-kit/pull/168
=> feat: add workload rollout restarts to UI

frontend/graph/conversions.go, frontend/graph/generated.go, frontend/graph/model/models_gen.go, frontend/graph/schema.graphqls, frontend/graph/schema.resolvers.go, frontend/webapp/graphql/queries/source.ts, frontend/webapp/package.json, frontend/webapp/yarn.lock
Following up after: https://github.com/odigos-io/odigos/pull/3028
Depends on: https://github.com/odigos-io/ui-kit/pull/183
This PR adds an option to manually override runtime info from the UI.
https://github.com/user-attachments/assets/683fc26d-a196-43d2-a51b-b9621b6178cc
=> feat: runtime override via UI

docs/setup/system-requirements.mdx
=> docs: add network requirements

common/envOverwrite/originalenv.go, common/envOverwrite/overwriter.go, k8sutils/pkg/envoverwrite/origenv.go
Just some cleanup and house-keeping. deleting unused functions and removing one more reference to "github.com/odigos-io/odigos/common/envOverwrite" which I am eager to delete 😄
Code compiles after removing unused functions
No
Internal refactor only
=> chore: remove unused functions

frontend/webapp/app/(overview)/layout.tsx, frontend/webapp/app/(overview)/overview/page.tsx, frontend/webapp/app/(overview)/service-map/page.tsx, frontend/webapp/hooks/metrics/useServiceMap.ts, frontend/webapp/package.json, frontend/webapp/utils/constants/props.ts, frontend/webapp/utils/constants/routes.tsx, frontend/webapp/yarn.lock
=> feat: add page for service map in UI

helm/odigos/templates/odigos-config-cm.yaml, helm/odigos/values.yaml
Adding input validation for profiles in helm `.values`
=> Helm profile input validation

frontend/webapp/package.json, frontend/webapp/yarn.lock
Includes a fix for Service Map DAG positions
=> chore: bump UI deps

frontend/webapp/components/lib-imports/overview-header.tsx, frontend/webapp/package.json, frontend/webapp/yarn.lock
Includes fix for absolute positioning of notification manager
=> chore: update @odigos/ui-kit to v0.0.53 and do clean up in OverviewHeader

odiglet/pkg/instrumentation/fs/agents.go
=> chore: improve nits in the init phase

frontend/webapp/package.json, frontend/webapp/yarn.lock
* crash related to `parseBooleanFromString` ([#233](https://github.com/odigos-io/ui-kit/issues/233)) ([e8bbd5c](https://github.com/odigos-io/ui-kit/commit/e8bbd5cc07e88576c1997518da4d8447353dad35))
* icon button not clicking ([#236](https://github.com/odigos-io/ui-kit/issues/236)) ([5bcedd6](https://github.com/odigos-io/ui-kit/commit/5bcedd6be4e1de384c1d7efe221f22fca872b661))
* metric edges z-index ([#235](https://github.com/odigos-io/ui-kit/issues/235)) ([579093b](https://github.com/odigos-io/ui-kit/commit/579093b9261206a04c99491ea003d87eab1472da))
=> chore: bump UI-Kit v0.0.56

.github/workflows/pr-policy.yml
=> Added a PR verification workflow

agents/python/setup.py
=> CORE-98 chore: bump version to v1.0.53

cli/cmd/resources/odiglet.go, helm/odigos/templates/odiglet/daemonset.yaml, helm/odigos/values.yaml
=> chore: adjust deviceplugin resources

.github/actions/cross-cloud-tests/action.yml, .github/workflows/cross-cloud-tests.yaml, tests-infrastructure/terraform/eks/main.tf, tests-infrastructure/terraform/eks/variables.tf
Added arm platform configuration for tofu plan (For EKS only)
Added arm support for cross-cloud-tests action
Added arm support for cross-cloud-tests workflow
=> Add ARM option to cross-cloud-tests

.github/workflows/create-release-candidate.yml
=> chore: fix

frontend/webapp/package.json, frontend/webapp/yarn.lock
=> chore: update @odigos/ui-kit to v0.0.93 and @types/react to v19.1.11 in package.json and yarn.lock

.github/workflows/push-release-branch-tag.yml
=> fix: tag detection from commit message

.github/workflows/nightly.yml
=> Manual run of single nightly - CORE-199

profiles/manifests/category-attributes.yaml
Similar to https://github.com/odigos-io/odigos/pull/3363
=> RUN-93: Add category attributes for Dynamo to profile

tests/common/assert/latest-odigos-version-installed.yaml
=> chore: fix latest installed - CORE-137

helm/odigos/templates/odigos-configuration-cm.yaml
=> chore: change ResourceSizePreset to resourceSizePreset

frontend/webapp/utils/constants/routes.tsx
=> fix: align the backend port to the origin port

autoscaler/controllers/nodecollector/sync.go
Fixes: CORE-271
small bug fix: check if datacollection collector group is nil before using it
=> fix: check for empty cg after fresh install

odiglet/pkg/ebpf/common.go
Add a call to memunlock before creating ebpf map in Odiglet
=> Call rlimit remove memlock

frontend/webapp/utils/constants/common.ts, frontend/webapp/utils/constants/routes.tsx
=> fix: include port for  ingress check

collector/providers/odigosk8scmprovider/provider.go
=> CORE-277 adding debounce to collector config updates

helm/odigos-central/templates/centralbackend/deployment.yaml, helm/odigos-central/templates/centralbackend/role.yaml, helm/odigos-central/templates/centralbackend/rolebinding.yaml, helm/odigos-central/templates/centralbackend/serviceaccount.yaml, helm/odigos-central/templates/centralui/deployment.yaml, scripts/release-charts.sh, tests/e2e/helm-upgrade/chainsaw-test.yaml
add missing Odigos Central Helm resources
=> helm(odigos-central): add central backend ServiceAccount, Role, RoleBinding resources 

profiles/manifests/semconv.yaml
=> feat: normalize http.method to http.request.method in semconv profile
