.gitignore
instrumentor/controllers/common.go
instrumentor/controllers/deployment_controller.go
instrumentor/controllers/statefulset_controller.go
ui/pages/api/apps.ts
ui/utils/crd.ts

Fix Deployment and StatefulSet Name Collision

---

cli/cmd/resources/instrumentor.go
instrumentor/controllers/common.go
instrumentor/main.go

Add ignore namespace option as a flag

---

cli/cmd/install.go
cli/cmd/resources/instrumentor.go
instrumentor/controllers/common.go

I noticed that I forgot to add cli option in odigos installation. It's totally OK to ignore this PR, with time Odigos will have lot of options and you may want to carefully choose how to do it.

Add missing option in CLI instruction

---

ui/.gitignore
ui/pages/api/dest/[destname].ts

This PR adds the removal of a secret (if exists) when deleting a destination.
This bug caused the creation of a destination with the same name as the deleted destination to fail.

bugfix: Remove secret when deleting destination

---

instrumentor/patch/dotnet.go
instrumentor/patch/golang.go
instrumentor/patch/java.go
instrumentor/patch/nodejs.go
instrumentor/patch/python.go
odiglet/example-app.yaml

This PR fixes a bug where instrumentation would panic when a deployment / statefulset has a null `.spec.containers[].resources.limits`

fix: Panic on null resource limits

---

ui/components/DestsGrid.tsx
ui/pages/dest/new/index.tsx

Feat: add destination search functions to odigos destination page
- Now users can search using either the short name or the display name
https://user-images.githubusercontent.com/44473671/235269380-2b4c230c-3225-4bc4-bb42-9a9e3fc2f894.mp4

destinations page: add search #37

---

.github/workflows/close-stale.yml

This PR adds a new GitHub workflow that handles the closing of stale issues and pull requests.

Add stale issues github workflow

---

.github/workflows/update-otel-versions.yml
odiglet/Dockerfile

This PR adds an automatic update of .NET instrumentation to the existing GitHub workflow

Auto update .net instrumentation

---

docs/README.md

Odigos documentation at [docs.odigos.io](https://docs.odigos.io) -> Odigos documentation is available at [docs.odigos.io](https://docs.odigos.io)

DOCS: Fixing correctness in README.md

---

cli/cmd/uninstall.go

- Issue: https://github.com/keyval-dev/odigos/issues/614
- Correction in output log
<br> 
- Removed ```\n``` from the ```log.print()``` to print the Tic mark(V) in same line
- Added ```l.Success()``` after ```log.Print("Rolling back odigos changes to namespaces")``` which is may be missing according to code
- Added ```l.Success()``` inside the ```else()``` block
<br> 
- **uninstall.go** (cli/cmd/uninstall.go)
<br>

fix: Corrected console output log

---

docs/mint.json

I updated `mint.json` https://keyval.dev/blog/  to https://odigos.io/blog. Because when visiting the https://keyval.dev/blog/ come up with odigos.io home page.

Updated blog link

---

cli/cmd/observability.go
cli/cmd/observability/backend/datadog.go
cli/cmd/observability/backend/grafana.go
cli/cmd/observability/backend/loki.go
cli/cmd/observability/backend/prometheus.go
cli/cmd/observability/backend/tempo.go
docs/adding-new-dest.mdx
docs/backends/lightstep.mdx
docs/backends/newrelic.mdx
docs/usage-reports.mdx

This PR fix the typos that is seen in multiple files.
```pseudo
specifiy > specify
invalud > invalid
mthod > method
informations > information
Cofiguring > Configuring
```

Chore: Typo fixed in multiple files

---

README.md

Currently it points to the Istio GoDoc status, but it should point to the correct location for Odigos.

Fixed link for the GoDoc badge in README.md

---

cli/cmd/install.go
cli/cmd/resources/namespace.go
cli/cmd/resources/owntelemetry.go

- Issue: #660 
- Update the error message for install of odigos if it is already installed
<br>
- Updated the code such that if  ```Namepace``` is found then print the updated error message and exit
<br>
- **install.go** (cli/cmd/install.go)

fix: exit if odigos is already installed

---

.github/workflows/main.yml

- Issue: #717 
- Remove the deprecated command ```set-output```, and update according to [GITHUB](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
<br>
- Replaced the deprecated command with this format: **```echo "{name}={value}" >> $GITHUB_OUTPUT```**
<br>
- **main.yml** (.github/workflows/main.yml)
<br>

Refactor: remove deprecated command set-output

---

cli/cmd/uninstall.go
docs/cli/odigos_uninstall.mdx

- Issue: #728 
- Add ```--yes``` flag to odigos uninstall to skip the confirmation prompt
<br>
- Defined a ```--yes``` flag in the ```init()``` function of uninstall.go file
- Added a condition to check if the flag value is changed or not, according to that continue for confirmation
<br>
- ```uninstall.go``` (cli/cmd/uninstall.go)
- ```odigos_uninstall.mdx``` (docs/cli/odigos_uninstall.mdx)
<br>

feat: add --yes flag to uninstall command

---

odiglet/Dockerfile
odiglet/base.Dockerfile

This PR speeds up the build time for the Odiglet component by using a base Docker image that contains all the needed dependencies.

Cache odiglet base image

---

odiglet/go.mod
odiglet/go.sum
odiglet/pkg/ebpf/go.go

This update version of go auto instrumentation adds the following:
* Fix the problem when HTTP status code is missing in some cases.
* Initial manual instrumentation support. Spans created manually in a Go application can mow be integrated with those collected automatically.

Update go auto instrumentation version and use WithGlobal

---

CONTRIBUTING.md

Fix #752
Added installation command before `build` command. i.e.,
```bash
npm install
```
[here](https://github.com/keyval-dev/odigos/blob/de3daf79e33f1f5ff8e5f97c3134aaeed01d6811/CONTRIBUTING.md?plain=1#L122)

[docs]: Improves contributions docs

---

autoscaler/controllers/gateway/config/elasticsearch.go
autoscaler/controllers/gateway/config/elasticsearch_test.go

This PR enables a flexible ES endpoints by removing hard-coded ES port in the endpoints section. This PR also sanitize/validate whether user input a valid URL or not by utilizing `url.Parse`. I'm wondering whether we do need to have a test or not since `url.Parse` function already have their own [test](https://cs.opensource.google/go/go/+/refs/tags/go1.21.6:src/net/url/url_test.go)
Please advise if we need more test cases
This PR will close #940

feat(elasticsearch): remove hard-coded port 9200, validate URL input

---

odiglet/Dockerfile
odiglet/Makefile
odiglet/debug.Dockerfile

After #1005, calling `go mod verify` can cause the build to break (since the downloaded packages are cached and modified by calling `make generate`)

Remove go mod verify in Odiglet Dockerfile

---

CONTRIBUTING.md
destinations/data/grafanacloudloki.yaml

Setting up my local env I noticed that some of the docs is a bit inconsistent. Mainly small nits:
- `CONTRIBUTING.md` steps for running the frontend are reversed. The frontend app must be built before one can run the Go web server.
- `CONTRIBUTING.md` shell snippets weren't all typed, and some of them included terminal fluff.
- One of the tooltips I saw during setup was not capitalized. YAML included some values that had redundant quotes - removed those while I was adding the capitalization.
Let me know if any of the changes go against your style. Happy to adjust.

style: tweak docs on setup (CONTRIBUTING.md)

---

cli/cmd/install.go

Stumbled upon a error message that has no newline char at the end and an error message that has redundant space(my editor highlights those).

style: add a newline to an error message

---

api/odigos/v1alpha1/collectorsgroup_types.go
autoscaler/controllers/datacollection/root.go
autoscaler/controllers/gateway/root.go

- **feat: implement status patch and use it instead of updating the whole data collection**
- **feat: generate client for colletorsgroup crd**
- **style: capitalize error messages**
Not exactly idiomatic to this codebase, but works™. Also the `genclient` is not required, but I saw that annotation on every other CRD during my investigation, so added it there for symmetry. Maybe it'll be useful in the future.

fix: fix autoscaler reconciliation loop with patching collector groups instead of updating them

---

docs/quickstart/generation-data.mdx

Fixes #1096
Added commands for consistency in the documentation:
```bash
kubectl get pods -n default
```
```bash
kubectl get pods -n odigos-system
```

Adds the missing commands in Generating data page

---

odiglet/Dockerfile
odiglet/debug.Dockerfile

I'm looking into updating Java Agent to v2.x soon. Until that, it doesn't hurt to upgrade it to the latest 1.x release.

chore: update Java Agent to the latest 1.x version

---

.github/workflows/e2e.yaml

It was introduced as a workaround fix until https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1143 is merged, due to an bug introduced via https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1139 which broke odigos ci

revert: using specific helm chart for e2e testing

---

Makefile
api/config/crd/bases/odigos.io_instrumentationconfigs.yaml
api/config/crd/bases/odigos.io_instrumentedapplications.yaml
cli/cmd/resources/crds/instrumentedapps.go
common/lang_detection.go
instrumentor/instrumentation/instrumentation.go
odiglet/pkg/kube/runtime_details/shared.go
procdiscovery/pkg/inspectors/langdetect.go

* Adding `unknown` to programming languages, indicating that we could not detect any of the currently supported languages.
* Create `InstrumentedApplication` object for cases where the language is unknown but the user requested to instrument.
* Add targets to Makefile to build and deploy the instrumentor

Add "unknown" programming language

---

autoscaler/main.go
common/consts/consts.go
common/go.mod
common/go.sum
common/pprof.go
destinations/go.mod
destinations/go.sum
instrumentor/main.go
odiglet/cmd/main.go
odiglet/go.mod
odiglet/go.sum
odiglet/pkg/instrumentation/fs/agents.go
procdiscovery/go.mod
procdiscovery/go.sum

* Initial integration of pprof in odiglet, autoscaler and instrumentor.
* Remove the library call to copy directories from the container to the host and use `cp` instead. The library call to `Copy` looked like it took an un-reasonable amount of un-released memory.

Pprof integration

---

k8sutils/pkg/env/env.go
odiglet/Makefile
odiglet/README.md
odiglet/debug.Dockerfile
odiglet/pkg/kube/instrumentation_ebpf/pods.go
odiglet/pkg/kube/manager.go
odiglet/pkg/kube/runtime_details/workload_predicate.go

The following changes are made to reduce memory consumption in odiglet:
* Only include pods within the same node in the cache. This will make sure that we are only reconciling pods that are in the same node as odiglet (instead of filtering them after querying).
* Avoid saving the managed fields for cached objects https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#TransformStripManagedFields
* Avoid querying ReplicaSet (which increased the memory consumption).

Reduce k8s cache memory usage

---

helm/odigos/templates/ui/deployment.yaml

by using localhost the ui is only accesible through localhost and non-routable from the outside

Use address 0.0.0.0 to ui

---

odiglet/cmd/main.go
odiglet/pkg/ebpf/go.go

Instead of assuming  an empty initial configuration, read the initial configuration from the CR

Read initial config of go auto instrumentation from instrumentationconfig CR

---

helm/odigos/templates/ui/role.yaml
helm/odigos/templates/ui/service.yaml
tests/e2e/README.md
tests/e2e/helm-chart/assert-odigos-installed.yaml
tests/e2e/multi-apps/assert-odigos-installed.yaml

This was already added in https://github.com/odigos-io/odigos-charts/pull/113.
However, during this time and the refactoring and migration to the new helm repo, this change was reverted and caused #1496.
Added an assertion for the UI service in e2e tests.

Fix UI service and role to support collectors metrics when installed via helm

---

instrumentor/controllers/instrumentationdevice/common.go

When instrumentor sees a runtime version it does not support, it should record this info into the status, and return `nil` from the reconcile since this issue is not an error we can retry

fix: do not return err on reconcile when its not retryable

---

common/instrumentationdevice.go
instrumentor/controllers/instrumentationdevice/manager.go

After instrumentor injects the instrumentation device and overriden envs to the workload template spec, these value might get over written if the user applies his workload manifest again.
At this point, the instrumentor should pick this up and insert odigos values back into the workload manifest template spec per each container.
Current reconciler only checks if something in the env changed to trigger recalculation, but we should also do it when something in the resource changes, so to inject the resource again if needed

fix: recalculate instrumentation device when overwritten

---

agents/nodejs-native-community/autoinstrumentation.js

See https://github.com/odigos-io/opentelemetry-node/pull/13
This PR starts the nodejs agent by calling a function, and supplying the distro name `'odigos-native-community'`, and a span processor for the community tier that uses batch span processor with OTLP exporter.
CI will pass once we merge the node agent PR

refactor: start nodejs agent with span processor

---

.dockerignore
cli/cmd/describe.go
cli/cmd/resources/ui.go
cli/pkg/kube/client.go
docs/cli/odigos_describe.mdx
frontend/Dockerfile
frontend/endpoints/describe.go
frontend/main.go
helm/odigos/templates/ui/clusterrole.yaml
k8sutils/pkg/describe/source.go

This can be used to run `odigos describe` in machines where `kubectl` may lacks permissions for some of the resources.
It runs the describe in the ui deployment which can access the relevant resources, and return it with http to the cli

feat: odigos describe remote flag to run the cluster

---

.github/workflows/e2e.yaml

Currently we are building the cli and docker images one after the other.
Since the cli takes ~30 seconds to build, we can benefit from doing it in parallel to the docker images, reducing 30 seconds from CI time

ci: build the cli in concurrent to the docker images

---

common/envOverwrite/overwriter.go
common/envOverwrite/overwriter_test.go
instrumentor/instrumentation/instrumentation.go
k8sutils/pkg/envoverwrite/origenv.go
tests/e2e/workload-lifecycle/01-assert-apps-installed.yaml
tests/e2e/workload-lifecycle/01-assert-instrumented.yaml
tests/e2e/workload-lifecycle/01-assert-runtime-detected.yaml
tests/e2e/workload-lifecycle/01-assert-workloads.yaml
tests/e2e/workload-lifecycle/01-generate-traffic.yaml
tests/e2e/workload-lifecycle/01-install-test-apps.yaml
tests/e2e/workload-lifecycle/01-wait-for-trace.yaml
tests/e2e/workload-lifecycle/02-assert-workload-update.yaml
tests/e2e/workload-lifecycle/02-update-workload-manifests.yaml
tests/e2e/workload-lifecycle/README.md
tests/e2e/workload-lifecycle/chainsaw-test.yaml

Handle few edge cases for env overwriter:
1. if language changes from something to unknown/ignored -> we must cleanup any env variables which were injected for the previous language, to sync them with the resource in use.
2. cleanup the env overwirtter annotation when it is empty
3. add e2e scenario to reproduce this case and verify it's behavior

fix: cleanup overwritten envs when language changes

---

.github/workflows/e2e.yaml

The `Install FE` step in `kubernetes-test` job for `e2e` workflow takes a whole minute to run, but it is only needed for cypress which runs in the `multi-apps`, `helm-chart` and `fe-synthetic` scenarios.
Run it conditionally so all the other 2 scenarios will finish 1 minute earlier

ci: e2e run install fe only for relevant scenarios

---

autoscaler/controllers/common/deployedcondition.go
autoscaler/controllers/datacollection/daemonset.go
autoscaler/controllers/gateway/root.go
k8sutils/pkg/describe/common.go
k8sutils/pkg/describe/odigos.go
scheduler/controllers/collectorsgroup_controller.go

This PR:
- record the status of autoscaler node collector info into the collector group condition to make it available for display.
- enhance the `odigos describe` command to include info about the node collector deployment:

feat: node collector info in odigos describe

---

destinations/data/qryn.yaml
docs/mint.json

- docs - add `gigapipe` destination to `mint.json` for it to show up in docs.
- ui - fix the destination category so it shows up in the UI with the other destinations as self hosted.
- ui - make the required qryn URL field first in the list, so it shows up first in ui

fix: some minors for qryn destination

---

cli/cmd/resources/scheduler.go
helm/odigos/templates/scheduler/clusterrole.yaml
scheduler/PROJECT
scheduler/controllers/collectorsgroup_controller.go
scheduler/controllers/instrumentationconfig_controller.go
scheduler/main.go

This PR moves the scheduler component to use `instrumentationconfigs` instead of `instrumentedapplications`. There is an effort to merge them any only use one CRD - the `instrumentationconfigs`.
The content of the object is not examined, it only checks if we have any `instrumentationconfigs` or not. Thus it should be safe.

chore(scheduler): use instrumentation config instead of application

---

autoscaler/controllers/collectorsgroup_controller.go
autoscaler/controllers/datacollection/configmap.go
autoscaler/controllers/datacollection/root.go
autoscaler/controllers/instrumentedapplication_controller.go
autoscaler/controllers/processor_controller.go
autoscaler/main.go
cli/cmd/resources/autoscaler.go
cli/cmd/resources/profiles.go

At the moment, dotnet and java native agent both use the device id in the `service.name` resource attribute, and this is replaced by the real service name and additional k8s attributes in the node processor later on.
eBPF instrumentations and OpAMP based agents injects the resource attribute directly and do not need the processor.
By default, the processor is enabled, but users that do not use the java native or dotnet may wish to disable it, and reduce load from the cluster. This PR adds a profile to do that.
This profile is temporary until we migrate dotnet and java to eBPF

feat: add profile to control if name processor is used or not

---

api/config/crd/bases/odigos.io_collectorsgroups.yaml
api/generated/odigos/applyconfiguration/odigos/v1alpha1/collectorsgroupspec.go
api/odigos/v1alpha1/collectorsgroup_types.go
autoscaler/controllers/collectorsgroup_controller.go
tests/e2e/workload-lifecycle/services/java-http-server/java-azul.Dockerfile
tests/e2e/workload-lifecycle/services/java-http-server/java-supported-docker-env.Dockerfile
tests/e2e/workload-lifecycle/services/java-http-server/java-supported-manifest-env.Dockerfile
tests/e2e/workload-lifecycle/services/java-http-server/java-supported-version.Dockerfile

1. add event filter for reconciler of collector group - to prevent endless reconcile loops
2. remove unused property from collector group CRD
3. pin version of java base image in tests for deterministic test result

fix: add event filter to prevent cg status from being reconciled indefinitely 

---

.vscode/launch.json
k8sutils/pkg/describe/odigos.go

This PR adds some handling for when the pipeline has not yet been created, making sure the `odigos describe` output is well formmated.
It also adds a human readable text to describe the expected state for cluster and node collectors

fix: odigos describe when pipeline is not created

---

opampserver/pkg/sdkconfig/collectorsgroup_controller.go

Once all the apps are un-instrumented we remove the node CG.
This causes repeated reconcile errors in the OpAmp server:
> {"level":"error","ts":1730064874.9696624,"caller":"controller/controller.go:316","msg":"Reconciler error","controller":"collectorsgroup","controllerGroup":"odigos.io","controllerKind":"CollectorsGroup","CollectorsGroup":{"name":"odigos-data-collection","namespace":"odigos-system"},"namespace":"odigos-system","name":"odigos-data-collection","reconcileID":"59801121-08a6-495c-b6af-38c8d02c6cf7","error":"CollectorsGroup.odigos.io \"odigos-data-collection\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s …

Ignore NotFound error for Node CG in OpAmp server

---

k8sutils/pkg/describe/source.go
k8sutils/pkg/describe/source/analyze.go

This PR fixes a bug in #1649 where a pointer would be accessed without first checking if it's nil

fix: check for empty pointers in describe

---

k8sutils/pkg/describe/source.go

Just a small bug fix, the cli describe command was showing runtime details of the `instrumentationConfig` instead of the value it should show of `instrumentedApplication`

fix: cli describe old runtime details showing content of new

---

odiglet/pkg/instrumentation/plugin.go

When a new pod is scheduled on a node, and the pod contains resource request for odigos device, then kubelet will trigger the Allocate function in odiglet.
Odiglet will try to `Get` the collectors group to calculate enabled signals, which are forwarded to the agent creation to enable / disable specific signals and avoid sending data from applications to a non-existing endpoint.
We must never return an error from the `Allocate` function, even if for some reason the collectors group had error, as it will make the pod non schedulable  with error: `UnexpectedAdmissionError`.
This PR makes it so if we have some error, we log it and start the agent with no enable signals, so odigos will never interfere with the pod start sequence

fix(odiglet): never return err from device allocate

---

instrumentor/controllers/instrumentationdevice/manager.go

When instrumented application updates, we only care if it's a change to the runtime details. this is achieved with the generation field on the object.

chore(instrumentor): event filter to ignore instrumented applications

---

instrumentor/controllers/instrumentationdevice/manager.go
instrumentor/controllers/startlangdetection/manager.go
instrumentor/controllers/utils/predicate.go
k8sutils/pkg/predicate/cgbecomesready.go
k8sutils/pkg/predicate/existence.go
k8sutils/pkg/predicate/objectname.go
k8sutils/pkg/predicate/onlyupdate.go
scheduler/controllers/destination_controller.go
scheduler/controllers/nodecollector_controller.go

Using the right event filters for controllers is very important to reduce resource utilization, avoid un-needed calls to api-server, and reduce chance to race conditions when multiple things changes at the same time.
We keep refining our controller event filters to achieve better stability for odigos.
Right now, we define our custom predicates near the controller where they are used, but this make it less easy to reuse existing common predicates and share code. This PR move some of the common and reuseable predicates to `k8sutils` module and refactor how they are being set up

refactor: extract common predicates to k8s utils

---

instrumentor/controllers/instrumentationdevice/collectorsgroup_controller.go
instrumentor/controllers/instrumentationdevice/manager.go
k8sutils/pkg/predicate/cgbecomesready.go

During the un-instrumentation of a large number of sources`reconcileSingleWorkload` may be called concurrently by the collectors group reconciler and the instrumented-application reconciler.
This race condition can cause the instrumentation device to be added right after its removal as demonstrated in the following log:
```
2024-11-08T12:18:23Z	INFO	removed instrumentation device from workload	{"controller": "instrumentationdevice-instrumentedapplication", "controllerGroup": "odigos.io", "controllerKind": "InstrumentedApplication", "InstrumentedApplication": {"name":"deployment-coupon","namespace":"simple-demo18"}, "namespace": "simple-demo18", "name": "deployment-coupon", "reconcileID": "a50d0c85-fd07-4896-84a3-817472fc3953", "namespace": "simple-demo18", "kind": …
```

Add event filter for instrumentation-device CG reconciler

---

instrumentor/controllers/deleteinstrumentedapplication/manager.go
instrumentor/controllers/deleteinstrumentedapplication/namespace_controller.go
instrumentor/main.go

The delete instrumented application controllers in instrumentor are responsible to delete the instrumentated application and instrumentation config once the workload and namespace labels are changed.
Specifically, it has a ns reconcile, and once detects labels change for a ns and the ns is uninstrumented, it loops on all deployments, ds and ss to delete any instrumentations for workloads that inheritaed instrumentation from ns.
There were few bugs fixed in this PR:
- the ns reconciler would list the workloads, and then iterate them one by one. This can take time. When UI instruments workloads, it starts by setting the label on the ns and then iterates the workloads. This mean that the ns reconciler might have read stale data and use it to delete instrumentation, even if the workload has …

fix: ns reconcile race condition on delete crds

---

instrumentor/controllers/instrumentationdevice/common.go

This is a minor refactor and improvement. instead of listing all collectors groups, and then iterating them to find the once we want, we simply fetch it by it's name. This also remove deprecated migration code from `v1.0.31` which is not supported for long time

refactor: get cg instead of listing and iterating

---

autoscaler/controllers/odigosconfig_controller.go
k8sutils/pkg/predicate/cm_changed.go

Following #1722, use the `ConfigMapDataChangedPredicate` in conjunction with `OdigosConfigMapPredicate` to only handle update events from our config map in autoscaler.

fix: Add predicate for the OdigosConfig reconciler in autoscaler

---

instrumentor/controllers/startlangdetection/namespace_controller.go
instrumentor/controllers/startlangdetection/odigosconfig_controller.go
instrumentor/controllers/startlangdetection/workload_controllers.go
k8sutils/pkg/workload/workloadkinds.go

Instead of passing an empty object and the object kind, pass only the object kind. Use `workload.ClientObjectFromWorkloadKind(objKind)` within the function.

enhance reconcileWorkload to only get the workload kind

---

autoscaler/controllers/datacollectiondaemonset_controller.go
autoscaler/controllers/destination_controller.go
autoscaler/controllers/gatewaydeployment_controller.go
autoscaler/controllers/instrumentedapplication_controller.go
autoscaler/controllers/processor_controller.go
autoscaler/controllers/secret_controller.go
k8sutils/pkg/predicate/objectname.go

This PR:
- shifts to use the common predicates in `k8sutils` over writing them specifically in the controllers.
- splits logic into smaller parts and combine them with `predicate.And` for better readability.
- adds few straight forward predicates to places where they are currently missing

refactor(autoscaler): use common predicates for event filters

---

cli/cmd/install.go
helm/odigos/Chart.yaml

For versions such as `v1.23.17-eks-ce1d5eb` we would get the following error:
> Error: chart requires kubeVersion: >= 1.20.15 which is incompatible with Kubernetes v1.23.17-eks-ce1d5eb

Include `-0` for the min version to allow EKS versions

---

cli/cmd/cloud.go
cli/cmd/describe.go
cli/cmd/diagnose.go
cli/cmd/install.go
cli/cmd/login.go
cli/cmd/logout.go
cli/cmd/profile.go
cli/cmd/resources/applyresources.go
cli/cmd/resources/odiglet.go
cli/cmd/root.go
cli/cmd/ui.go
cli/cmd/uninstall.go
cli/cmd/upgrade.go
cli/cmd/version.go
cli/pkg/autodetect/kind.go
cli/pkg/cmd_context/client.go
cli/pkg/cmd_context/cluster_info.go
cli/pkg/kube/client.go
k8sutils/pkg/consts/consts.go

Add `PersistentPreRun` which will be inherited by all sub-commands of the root command.
Perform a client initialzation in that function and set the cluster kind and k8s version as well - so they can be used by all commands. Both the kube client and the cluster details are set on the command context and can be used by all the commands.
The helper function from k8sutils `GetKubernetesVersion` can't be used outside of the cluster by the CLI since it as using a rest client which states:
> // InClusterConfig returns a config object which uses the service account
// kubernetes gives to pods. It's intended for clients that expect to be
// running inside a pod running on kubernetes. It will return ErrNotInCluster
// if called from a process not running in a kubernetes environment.
func …

Add PersistentPreRun to the root CLI cmd to set the kube client and cluster details once for all commands

---

instrumentor/instrumentation/instrumentation.go
k8sutils/pkg/consts/consts.go

Simplified the `SetInjectInstrumentationLabel` function by removing the `odigosTier` variable and the conditional check for the community tier, ensuring that the instrumentation label is always injected.

feat: enable webhook also for enterprise

---

.github/workflows/e2e.yaml

Get rid of these warnings in odigos CI:
> build-odigos-imagesThe following actions use a deprecated Node.js version and will be forced to run on node20: actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default

ci: update version for download-artifact

---

frontend/main.go

Revert "[GEN-1743]: serve root file for "404 file not found""

---

common/config/root.go
common/config/testdata/debugexporter.yaml
common/config/testdata/minimal.yaml

The value in `max_recv_msg_size_mib` for otlp receiver in cluster collector config should be in alignment with the memory the deployment has to run. 
It was set accidentally to `128 * 1024 * 1024` (e.g. value in bytes), instead of intended `128` which is a reasonable number to use.
before this change, the value being populated in the config would be `134217728` MiB which makes no sense

fix: set max_recv_msg_size_mib to value in correct units

---

docs/quickstart/next-steps.mdx

I found that the destinations in `backends-overview.mdx` didn't match those in this file so I added them. Also alphabetically sorted the cards.

Add missing destination providers

---

frontend/webapp/containers/main/destinations/destination-form-body/dynamic-fields/index.tsx

This pull request includes a modification to the `DestinationDynamicFields` component in the `frontend/webapp/containers/main/destinations/destination-form-body/dynamic-fields/index.tsx` file. The change updates the handling of the `Dropdown` input type to ensure proper value assignment and selection.
Changes to `DestinationDynamicFields` component:
* [`frontend/webapp/containers/main/destinations/destination-form-body/dynamic-fields/index.tsx`](diffhunk://#diff-c17889e1ffea148a206f57df5da9f8cc755e7e522a9057a339f6887c01ed5815L19-R19): Updated the `Dropdown` input type to set the `value` prop correctly and simplified the `onSelect` callback to pass only the selected option's value.

[GEN-1986]: fix values for destination dropwdowns

---

frontend/webapp/containers/main/destinations/add-destination/index.tsx

This pull request to `frontend/webapp/containers/main/destinations/add-destination/index.tsx` includes changes to improve the user experience by addressing loading states and preventing double-click issues. The most important changes include adding a loading spinner, modifying button states, and adjusting modal behavior.
Loading state improvements:
* Added `FadeLoader` and `CenterThis` to display a loading spinner during asynchronous operations.
* Introduced `isLoading` state to manage and display loading status, replacing the previous `sourcesLoading` and `destinationsLoading` states. [[1]](diffhunk://#diff-a5ff632e01d3e161b70dce2f959db69fd1893edb484af12b7849810487347001L42-R48) [[2]](diffhunk://#diff-a5ff632e01d3e161b70dce2f959db69fd1893edb484af12b7849810487347001R58-R59)
Button and …

[GEN-1978]: improve UX for end-of-onboarding

---

CONTRIBUTING.md
Makefile
collector/builder-config.yaml
collector/odigosotelcol/components.go
collector/odigosotelcol/go.mod
collector/odigosotelcol/go.sum
common/config/nop.go
common/config/root.go
common/dests.go
tests/debug-exporter.yaml
tests/nop-exporter.yaml

This PR:
- removes the deprecated and unused logging exporter, which is replaced with the debug exporter which we do use.
- removed the deprecated `ballast` extension which  we don't use and is deprecated in favor of `GOMEMLIMIT` which we do use.
- adds the `nop` exporter which is useful for development and testing (for example - load scenarios)
- adds documentation in `CONTRIBUTING.md` regarding how to use the debug and nop destination for development.

feat: add nop destination and cleanup deprecated components

---

frontend/webapp/containers/main/destinations/add-destination/configured-destinations-list/index.tsx
frontend/webapp/containers/main/sources/source-drawer-container/index.tsx
frontend/webapp/reuseable-components/condition-details/index.tsx
frontend/webapp/reuseable-components/data-card/data-card-fields/index.tsx
frontend/webapp/reuseable-components/data-tab/index.tsx
frontend/webapp/reuseable-components/extend-icon/index.tsx
frontend/webapp/reuseable-components/monitors-icons/index.tsx
frontend/webapp/reuseable-components/nodes-data-flow/nodes/base-node.tsx

This pull request includes several changes focused on improving the user interface and functionality of the `frontend/webapp` components. The most important changes include refactoring the `ConfiguredDestinationsList` component, enhancing the `DataTab` component, and adding new features to handle specific conditions in the `SourceDrawer`.
* [`frontend/webapp/containers/main/destinations/add-destination/configured-destinations-list/index.tsx`](diffhunk://#diff-f5288a6a2e6ccce16445bdd7486abda1bbd12662ea0e0bc846ff0f60b85b12f9R4-R8): Refactored `ConfiguredDestinationsListItem` to use `DataTab` instead of custom-styled components, simplifying the code and improving maintainability. [[1]](diffhunk://#diff-f5288a6a2e6ccce16445bdd7486abda1bbd12662ea0e0bc846ff0f60b85b12f9R4-R8) …

[GEN-1837]: "other agent" for new UI

---

instrumentor/controllers/instrumentationdevice/manager.go
instrumentor/controllers/instrumentationdevice/pods_webhook.go
instrumentor/go.mod
k8sutils/pkg/container/container.go
odiglet/pkg/kube/instrumentation_ebpf/shared.go

For dotnet and OSS java which currently relies on the resource to inject the device id in odiglet, and then resolves it from kublet to the desired service name

feat: inject OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES via webhook

---

.github/workflows/release.yml
scripts/release-charts.sh

This PR stops syncing the previous helm repo at https://github.com/odigos-io/odigos-charts
The crds there are not relevant for long time, and the new helm repo is available for 5 month to migrate. see [this blog post](https://odigos.io/blog/helm-chart-repository-deprecation).
This PR completes the migration

ci: deprecate old chart repo syncs

---

cli/cmd/resources/scheduler.go
helm/odigos/templates/scheduler/clusterrole.yaml
helm/odigos/templates/scheduler/role-binding.yaml
helm/odigos/templates/scheduler/role.yaml
scheduler/main.go

In this PR:
- move destinations and collectorsgroup rbac permission to be role (on odigos ns) instead of clusterrole. These live anyway only in our ns, but it looks better in rbac reviews.
- removed unused create/delete/update/patch for the destinations, as we only read them.
- currently the leader election role brings in configmaps permissions, but I also added the permissions we need for the reconcilers so not to mix unrelated things. we will need to also understand and address the leader election role later on.
- removed the finalizers permissions, as we don't use finalizers and it's unused.
- created some consts in cli files for better structure to the references
- synced helm files with the changes
- tested both helm and cli locally to make sure it works
InstrumentationConfig is left …

chore: narrow down the rbac permissions for schedualer

---

autoscaler/PROJECT
autoscaler/controllers/datacollection/configmap.go
autoscaler/controllers/datacollection/configmap_test.go
autoscaler/controllers/datacollection/root.go
autoscaler/controllers/gateway/deployment.go
autoscaler/controllers/instrumentedapplication_controller.go
autoscaler/main.go
cli/cmd/resources/autoscaler.go
helm/odigos/templates/autoscaler/clusterrole.yaml

Part of the effort to retire instrumentedapplication
This object behaves the same, so no changes in functionality is expected.
Updated the RBAC roles and cleaned up unused permissions while at it (we need to do a bigger rbac swap in a different PR).
Tested it to work with both cli and helm (with logs destination that triggers change in collector cm to collect logs).

refactor: use instrumentationconfig in autoscaler

---

frontend/graph/conversions.go
frontend/graph/generated.go
frontend/graph/model/models_gen.go
frontend/graph/schema.graphqls
frontend/graph/schema.resolvers.go
frontend/webapp/containers/main/actions/action-drawer/build-drawer-item.ts
frontend/webapp/containers/main/actions/action-drawer/index.tsx
frontend/webapp/containers/main/sources/source-drawer-container/index.tsx
frontend/webapp/graphql/queries/compute-platform.ts
frontend/webapp/types/actions.ts
frontend/webapp/types/common.ts

This pull request includes several changes to the `frontend/graph` and `frontend/webapp` directories to introduce the `PipelineAction` type and improve handling of conditions in the application. Below are the most important changes:
* Added `PipelineAction` type to replace `IcaInstanceResponse` in the GraphQL schema and resolvers. This new type includes an `ActionStatus` field with conditions. [[1]](diffhunk://#diff-642ccd7ed71fdfa394bd7f7fd99c9c33e20ff18c876a91cb989d379a44390469L82-R95) [[2]](diffhunk://#diff-642ccd7ed71fdfa394bd7f7fd99c9c33e20ff18c876a91cb989d379a44390469L244-L249) [[3]](diffhunk://#diff-bc07b91dedd1782d9ddbbb6374ad97c7604f9a267de5174645723d863c732f80L211-R211) [[4]](diffhunk://#diff-8e6e95029056db2c0301fc338e0ca5a04356ce5d45ee9514bbd167f2d85bae70L138-R138) …

[GEN-2111]: read & display "conditions" for actions

---

instrumentation/manager.go

In case of an error in the runtime-detector module, the process events channel is closed.
Add proper handling of the channel being closed.

Handle closed processes details channel gracefully

---

cli/cmd/resources/odigosconfig.go
k8sutils/pkg/profiles/profile.go
k8sutils/pkg/profiles/utils.go
scheduler/controllers/odigosconfig/odigosconfig_controller.go

This PR makes it so that we reconcile sizing profiles in schedualer into effective config, instead of modifying the config object itself in cli.
It give the following benefits:
- works with helm (vs current implementation that only works with cli).
- cleaner code - the code that sets values for profile is now part of the profile for easier navigation in the code base
- remove complication from cli regarding handling these values

feat: reconcile effective collectors sizing profiles 

---

cli/cmd/resources/autoscaler.go
cli/cmd/resources/instrumentor.go
helm/odigos/templates/autoscaler/deployment.yaml
helm/odigos/templates/instrumentor/deployment.yaml

This is so we can add new keys to `odigos-deployment` without warring about them blowing up deployments that map them as `envFrom`. This PR makes it so we can only map what we actually use

chore: map only needed keys from odigos-deployment in envFrom

---

autoscaler/controllers/gateway/deployment.go
autoscaler/main.go
cli/cmd/resources/autoscaler.go
cli/cmd/resources/instrumentor.go
cli/cmd/resources/odigosdeployment.go
cli/cmd/upgrade.go
common/consts/consts.go
k8sutils/pkg/consts/consts.go
k8sutils/pkg/env/env.go
k8sutils/pkg/getters/odigosversion.go

Cleanup, in prepration for adding more keys to the `odigos-deployment` configmap

chore: move common strings for "odigos-deployment" cm to consts and use them

---

cli/cmd/resources/odigosdeployment.go
helm/odigos/templates/odigos-deployment.yaml
k8sutils/pkg/consts/consts.go
k8sutils/pkg/describe/odigos.go
k8sutils/pkg/describe/odigos/analyze.go
k8sutils/pkg/describe/odigos/resources.go
k8sutils/pkg/installationmethod/installationmethod.go

This PR adds "instllation method" to `odigos-deployment` config map, so we can reliably know if the current installation is deployed via "helm" or "odigos-cli".
We can later use this info to warn or block usages which we do not support and might end up with a broken deployment or odigos.
This PR also adds the installation method and tier to the describe cli command:
```
go run -tags=embed_manifests . describe                           
Odigos Version: v1.0.142
Tier: community
Installation Method: helm
....
```

feat: record installation method into odigos-deployment

---

cli/pkg/kube/client.go

This code is for migration from `v1.0.23` to > `v1.0.23` which is no longer relevant

chore(cli): delete old deprecated code for very old versions

---

frontend/webapp/app/(overview)/overview/page.tsx
frontend/webapp/components/main/header/index.tsx
frontend/webapp/components/overview/all-drawers/cli-drawer.tsx
frontend/webapp/hooks/notification/useSSE.ts
frontend/webapp/hooks/tokens/index.ts
frontend/webapp/hooks/tokens/useTokenTracker.ts
frontend/webapp/reuseable-components/status/index.tsx
frontend/webapp/store/useConnectionStore.ts
frontend/webapp/store/useNotificationStore.ts
frontend/webapp/styles/theme.ts
frontend/webapp/utils/constants/index.tsx
frontend/webapp/utils/constants/numbers.ts
frontend/webapp/utils/functions/resolvers/index.ts
frontend/webapp/utils/functions/resolvers/is-over-time/index.ts
frontend/webapp/utils/functions/resolvers/is-within-time/index.ts

This pull request introduces several changes to enhance the token tracking system, improve connection status handling, and refactor the notification system. The most important changes include adding a new hook for token tracking, updating the connection store, and modifying the status component to handle different notification types.
* Added `useTokenTracker` hook to monitor token expiration and trigger notifications (`frontend/webapp/hooks/tokens/useTokenTracker.ts`).
* Updated `useTokenCRUD` import to include `useTokenTracker` (`frontend/webapp/hooks/tokens/index.ts`).
* Refactored `useConnectionStore` to include new state values and setters for SSE and token statuses (`frontend/webapp/store/useConnectionStore.ts`).
* Modified `useSSE` hook to use the new `setSseStatus` method for …

[GEN-2187]: notify in UI about expiring/expired token

---

frontend/webapp/reuseable-components/dropdown/index.tsx

This pull request includes a small change to the `frontend/webapp/reuseable-components/dropdown/index.tsx` file. The change adds a `z-index` property to the `AbsoluteContainer` styled component to ensure proper stacking order.
* [`frontend/webapp/reuseable-components/dropdown/index.tsx`](diffhunk://#diff-707b6e11fbf977d74c45816fab07924a0eaa2d139b296cc58b74c98fd76f463dR194): Added `z-index: 1` to the `AbsoluteContainer` styled component to manage stacking context.

fix: z-index for dropdown component

---

frontend/webapp/hooks/sources/useSourceFormData.ts

This pull request includes a small change to the `frontend/webapp/hooks/sources/useSourceFormData.ts` file. The change updates the handling of namespace selection within the `useSourceFormData` hook.
* [`frontend/webapp/hooks/sources/useSourceFormData.ts`](diffhunk://#diff-cd2bc3c9473adfb41833260ef193384279ed75ef4b6c6866290ca78a174471e7L94-R94): Replaced the `onSelectNamespace` function call with `setSelectedNamespace` when clicking "select all" on a namespace.

[GEN-2227]: fix namespace selection logic in useSourceFormData hook

---

frontend/graph/schema.resolvers.go
frontend/main.go
frontend/services/actions/addclusterinfo.go
frontend/services/actions/deleteattribute.go
frontend/services/actions/errorsampler.go
frontend/services/actions/latencysampler.go
frontend/services/actions/piimasking.go
frontend/services/actions/probabilisticsampler.go
frontend/services/actions/renameattribute.go
frontend/services/destinations.go
frontend/services/instrumentationrule.go
frontend/services/namespaces.go

This pull request focuses on updating the namespace handling in the `frontend/graph/schema.resolvers.go` file and related files to use the current namespace dynamically instead of a hardcoded default. The main changes involve replacing the constant `DefaultOdigosNamespace` with the dynamic value obtained from `env.GetCurrentNamespace()`.
Namespace handling updates:
* [`frontend/graph/schema.resolvers.go`](diffhunk://#diff-8e6e95029056db2c0301fc338e0ca5a04356ce5d45ee9514bbd167f2d85bae70R22-R36): Replaced hardcoded `consts.DefaultOdigosNamespace` with `env.GetCurrentNamespace()` for various Kubernetes client operations. [[1]](diffhunk://#diff-8e6e95029056db2c0301fc338e0ca5a04356ce5d45ee9514bbd167f2d85bae70R22-R36) [[2]](diffhunk://#diff-8e6e95029056db2c0301fc338e0ca5a04356ce5d45ee9514bbd167f …

[GEN-2226]: replace DefaultOdigosNamespace constant with dynamic GetCurrentNamespace function

---

frontend/graph/generated.go
frontend/graph/model/models_gen.go
frontend/graph/schema.graphqls
frontend/services/instrumentationrule.go
frontend/webapp/containers/main/instrumentation-rules/rule-drawer/build-card.ts
frontend/webapp/containers/main/instrumentation-rules/rule-drawer/build-drawer-item.ts
frontend/webapp/containers/main/instrumentation-rules/rule-drawer/index.tsx
frontend/webapp/graphql/queries/compute-platform.ts
frontend/webapp/types/instrumentation-rules.ts
frontend/webapp/utils/constants/string.tsx

This pull request introduces several changes to the `frontend/graph` and `frontend/webapp` directories to add new fields and functionality related to `InstrumentationRule`. The most important changes include adding the `mutable` and `profileName` fields to the `InstrumentationRule` type, updating the GraphQL schema and queries, and modifying the frontend components to handle these new fields.
* Added `mutable` and `profileName` fields to the `InstrumentationRule` struct in `frontend/graph/model/models_gen.go` and updated the GraphQL schema in `frontend/graph/schema.graphqls`. [[1]](diffhunk://#diff-642ccd7ed71fdfa394bd7f7fd99c9c33e20ff18c876a91cb989d379a44390469R292-R293) [[2]](diffhunk://#diff-bc07b91dedd1782d9ddbbb6374ad97c7604f9a267de5174645723d863c732f80R120-R121)
* Updated the …

[GEN-2224] add "mutable" and "profileName" fields to InstrumentationRule model

---

api/generated/odigos/applyconfiguration/odigos/v1alpha1/attributecondition.go
api/go.mod
api/odigos/v1alpha1/instrumentationconfig_types.go
docs/api-reference/odigos.io.v1alpha1.mdx

It was only used to pull in attribute.Key which is a string.
This change reduces a bit our dependency management and complexity

chore: remove direct dependency of api module on otel

---

api/config/crd/bases/odigos.io_instrumentedapplications.yaml
api/odigos/v1alpha1/instrumentationconfig_types.go
api/odigos/v1alpha1/instrumentedapplication_types.go
docs/api-reference/odigos.io.v1alpha1.mdx
helm/odigos/templates/crds/odigos.io_instrumentedapplications.yaml

* Mark `InstrumentedApplication` and all its related fields as deprecated.
* Move `ProcessingState`  (which is not deprecated) to `instrumentationconfig_types.go`.

mark instrumentedApplication as deprecated

---

.github/workflows/publish-modules.yml

This will publish the Red Hat-based images from https://github.com/odigos-io/odigos/pull/2252 alongside our normal released images.
Logic:
* Add 2 matrix values: `Dockerfile` and `Dockerfile.rhel` to run for each service
* Add a matrix value for each service: `['autoscaler', 'scheduler', 'instrumentor', 'collector', 'odiglet', 'ui']`
* Add the appropriate `summary` and `description` to each service in the `include` section (used for image labels)
This should produce 12 jobs from the current 6.
I tested this matrix approach in a simple PR https://github.com/damemi/odigos/pull/5. The output showed 12 tests as expected: https://github.com/damemi/odigos/actions/runs/12938761839?pr=5 In addition, each test adds a simple logging step to confirm that `summary`, `description`, and `runner` were …

Add Red Hat UBI images to publish-modules workflow

---

tests/common/assert/simple-demo-runtime-detected.yaml
tests/e2e/source/08-assert-runtime-detected.yaml
tests/e2e/source/09-assert-runtime-detected.yaml
tests/e2e/workload-lifecycle/01-assert-runtime-detected.yaml

To reduce flakiness, and adjust the tests to the updated runtime detection.

use envFromContainerRuntime in e2e asserts

---

.github/workflows/check-links.yml
.github/workflows/golangci-lint.yml

This pull request includes changes to the GitHub Actions workflows to modify when certain actions are triggered. The most important changes include removing the `push` event trigger for the `check-links` and `golangci-lint` workflows.
Changes to GitHub Actions workflows:
* [`.github/workflows/check-links.yml`](diffhunk://#diff-defd48946787cc6a6a360e44775e44ff3a68817a47f9c8606e5150e54e378ac0L4-L5): Removed the `push` event trigger that was set to trigger on the `main` branch.
* [`.github/workflows/golangci-lint.yml`](diffhunk://#diff-d9a956120ac84289d2650137f64bd8f0893331de05e44cc41899dd984c9e0d48L3-L5): Removed the `push` event trigger that was set to trigger on the `main` branch.

ci: run golanglint only on PR (removed push to main)

---

.github/dependabot.yml

This pull request includes significant updates to the `.github/dependabot.yml` configuration file, primarily focusing on restructuring the package ecosystems and directories for dependency updates.
Key changes include:
* Added new directories for `gomod` package-ecosystem, including `/destinations`, `/instrumentation`, `/k8sutils`, `/procdiscovery`, and `/profiles`.
* Consolidated multiple `gomod` configurations into a single entry, simplifying the schedule and grouping patterns.
* Changed the update schedule for `gomod` dependencies from Monday to Sunday to align with other dependencies.
* Removed multiple redundant `gomod` entries that were previously spread across different directories, streamlining the configuration.
* Removed unnecessary group configurations for `pip` and `gomod` …

ci: edit dependabot config

---

instrumentor/controllers/deleteinstrumentationconfig/instrumentationconfig_controller.go

When upgrading from a version without the Sources support, to a version with them (starting from v1.0.144), we need to consider the instrumentation labels on the workloads and namespaces before deleting instrumentationConfig,
Before this fix, instrumentationConfigs are getting deleted on upgrades (before the Source are created by the migration controller).

fix: consider the instrumentation labels when deleting instrumentationConfig

---

autoscaler/controllers/datacollection/daemonset.go
tests/common/assert/pipeline-ready.yaml

Similar to #1989 but for the data collection.

Set GOMAXPROCS according to the cpu limit in data-collection

---

docs/setup/installation-options.mdx
docs/setup/system-requirements.mdx

To be published with v1.0.146 and blog post https://github.com/odigos-io/landing-page/pull/163

Update docs on OpenShift

---

docs/instrumentations/golang/ebpf.mdx

This pull request includes a small change to the `docs/instrumentations/golang/ebpf.mdx` file. The change updates the link for the `github.com/IBM/sarama` module to point to its GitHub repository instead of its Go package documentation.
* Updated the link for `github.com/IBM/sarama` to point to the GitHub repository.

fix: replace IBM Sarama URL in docs to fix check-links

---

docs/setup/system-requirements.mdx

This pull request includes a minor update to the `docs/setup/system-requirements.mdx` file. The change updates the link for Red Hat OpenShift to point to a more specific container stack detail page.
Documentation update:
* [`docs/setup/system-requirements.mdx`](diffhunk://#diff-dce1fa0a01a33f246fafe30474920046e4a74e42bb49621c59e96063ff04fd44L27-R27): Updated the Red Hat OpenShift link to point to the container stack detail page instead of the general technologies page.

Replace OpenShift docs URL with Odigos catalog on OpenShift

---

frontend/graph/generated.go
frontend/graph/model/models_gen.go
frontend/graph/schema.graphqls
frontend/services/describe/source_describe/source_describe.go
frontend/webapp/graphql/queries/describe.ts
frontend/webapp/hooks/describe/useDescribeSource.ts
frontend/webapp/types/describe.ts
k8sutils/pkg/describe/source.go
k8sutils/pkg/describe/source/analyze.go
k8sutils/pkg/describe/source/resources.go
k8sutils/pkg/describe/source/source.go

Update describe to inspect the Sources instead of relying on the deprecated labels.

fix: update describe to rely on Sources

---

cli/cmd/sources.go

The new `sources` cli command was reusing the `namespaceFlag` of the install command, setting it to default value `default`.
This leads to `odigos install` trying to install odigos into default ns if run without setting this flag.

fix: sperate cli namespace flag for sources and install

---

frontend/webapp/cypress/constants/index.ts
frontend/webapp/cypress/e2e/04-destinations.cy.ts
frontend/webapp/cypress/e2e/05-actions.cy.ts
frontend/webapp/cypress/e2e/06-rules.cy.ts
tests/e2e/ui/chainsaw-test.yaml

This pull request includes changes to the Cypress tests and an E2E test configuration to use a new namespace for testing. The most important changes include updating the namespace in various test files and the E2E test configuration.
Changes to Cypress tests:
* [`frontend/webapp/cypress/constants/index.ts`](diffhunk://#diff-ffe3e5bc9ff7bba75f2007551dd3e69fa93e9638a7fb62ceec23414f8333f491R24): Added `ODIGOS_TEST` to the `NAMESPACES` export.
* [`frontend/webapp/cypress/e2e/04-destinations.cy.ts`](diffhunk://#diff-6f34bd7eb1cce2b4683938973757c4b0e80921234633a259cd17674c0805ca1bL8-R8): Changed the namespace from `ODIGOS_SYSTEM` to `ODIGOS_TEST` for the Destinations CRUD tests.
* [`frontend/webapp/cypress/e2e/05-actions.cy.ts`](diffhunk://#diff-adc830d3310d3ba00c598b867a2b4f782e4fc6d3147fdb7af3 …

ci: Add 'odigos-test' namespace for CLI installation

---

api/k8sconsts/envvars.go
distros/yamls/python-enterprise.yaml
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/env.go
instrumentor/controllers/agentenabled/podswebhook/mount.go
k8sutils/pkg/container/container.go
odiglet/pkg/ebpf/distribution_matcher.go
odiglet/pkg/ebpf/reporter.go
odiglet/pkg/ebpf/resolvers.go
tests/common/assert/simple-demo-instrumented.yaml

As part of the effort to remove instrumentation device, this PR:
- add environment variable to containers, `ODIGOS_DISTRO_NAME` to describe the name of the distro injected to the pod.
- migrate ebpf manager to match distribution based on the new environment variable with fallback to device so not to break existing users.
- fix missing agent directory needed in python
- remove device from 4 distros that do not inject any env variables - only need the `/var/odigos` mount, or not.

chore: migrate ebpf manager from device to distro name env

---

Makefile
tests/e2e/README.md

Just to make troubleshooting easier when running the tests locally.

chore: add make target for e2e tests grafana

---

instrumentor/controllers/agentenabled/rollout/rollout.go
tests/e2e/source/chainsaw-test.yaml
tests/e2e/source/wait_for_rollout.sh

* Reduce flakiness in the `sources` e2e test by waiting 1 second between rollouts. This cause flakiness since we are now using a timestamp annotation to trigger a rollout. This timestamp has a resolution of seconds, hence if the test progresses through 2 steps in less than a second we'll have a missing rollout.
* If a rollout fails when we want to un-instrument a workload, add requeue.

fix: requeue if failed to trigger an un-instrument rollout

---

distros/distro/oteldistribution.go
distros/yamls/dotnet-community.yaml
distros/yamls/dotnet-legacy.yaml
distros/yamls/java-community.yaml
distros/yamls/java-ebpf-instrumentations.yaml
distros/yamls/java-enterprise.yaml
distros/yamls/nodejs-community.yaml
distros/yamls/nodejs-enterprise.yaml
distros/yamls/python-community.yaml
distros/yamls/python-enterprise.yaml
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/env.go
instrumentor/controllers/agentenabled/podswebhook/otelresource.go

This PR migrate the code in webhook that injects OTEL_RESOURCE_ATTRIBUTE and OTEL_SERVICE_NAME to the 3 relevant distributions.
It moves code from the main pods_webhook.go file to internal files for better organization

refactor: migrate otel resource env to distro

---

autoscaler/controllers/collectorsgroup_controller.go

If for any reason, the data-collection daemonset, gateway deployment, or one of the config maps is deleted, then it's not re-created at the moment.
This PR makes it so they are.
We had a bug where the collectors group would get deleted, and it also deleted the daemonset. then if the collectors group is re-created immediately, the daemonset would stay deleted and odigos would not work

fix: recreate autoscaler resources if deleted or modified

---

k8sutils/pkg/node/node.go
odiglet/cmd/main.go
odiglet/odiglet.go
odiglet/pkg/instrumentation/fs/agents.go

This does 2 things in the Odiglet:
* **Make SELinux calls for openshift last in the init phase.** These functions `chroot` to the host directory to run selinux commands that update the agent permissions, so they are readable by pods. This `chroot` was preventing the k8s client from initializing with `open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`. Moved last so the `chroot` doesn't mess up future changes.
* **Initializes the k8s clientset in the main odiglet function.** This allows the same clientset to be passed through to the init phase (which uses it to apply labels to nodes) and the odiglet controller. Doing so makes `clientset` an argument to functions like `odiglet.New` and `k8snode.AddLabelToNode`, the latter of which is just a helper which …

odiglet: Initialize clientset at startup and do OpenShift selinux changes last

---

instrumentor/controllers/agentenabled/podswebhook/mount.go

In case the webhook is triggered more than once

fix: avoid adding the mount paths multiple times

---

instrumentation/manager.go

Once the Odiglet is shutting down, call the `reporter.OnExit` callback from the ebpf instrumentation manager.
When the odiglet is doing a rollout (in an upgrade for example) the ebpf probes are unloaded and loaded - this creates a time period when there is not active instrumentation - hence this change will remove the instrumentation instances corresponding to these instrumentations in that time period.

delete ebpf instrumentation instances once odiglet shuts down

---

cli/cmd/upgrade.go

If using the default (empty/docker.io) prefix from previous versions, update it to `registry.odigos.io` and drop `keyval/` prefix from stored image names

Migrate existing configs to use new registry and drop keyval prefix

---

docs/setup/installation-options.mdx

This is an openshift-specific setting, and it can be different depending on the cluster, so there isn't much we can guide users on. But making them aware of the right service to expose is helpful.
In my AWS OpenShift cluster, for example, I needed to set `tls.termination: edge` manually on the Route (it doesn't seem to be a cli setting in `oc expose`).

Add OpenShift docs note on exposing UI in-cluster with Routes

---

.gitignore
cli/cmd/sources.go
docs/cli/odigos_sources_delete.mdx
docs/cli/odigos_sources_update.mdx

Currently, the `odigos sources delete` and `odigos sources update` commands only accept flags that identify Sources based on the Workload they instrument. This is useful when the Source name might not be known (such as Sources that were created with a random name by the UI), and it also allows batch-deleting Sources (for example, deleting all Sources that instrument a StatefulSet, etc)
This adds an optional argument to specify a Source explicity by its name to these commands.
It also updates the help text (and docs) for these commands with examples of usage in individual vs batch scenarios.

cli: Support deleting/updating individual Sources by name

---

.github/workflows/release-artifactregistry.yml

Trying to run the release workflow after https://github.com/odigos-io/odigos/pull/2484, but the action only checks out the repo at the given tag.
So, trying to tag `v1.0.155` from `main` (where the creds files are gitignore'd), still ends up just cloning the repo at `1.0.155`
This also removes redundant steps from the current main release flow. These will soon be merged into one workflow once we permanently drop dockerhub builds

Let cli Artifact Registry release run from a different tag

---

.github/workflows/openshift-preflight.yml
.github/workflows/release-artifactregistry.yml

Automatically trigger OpenShift certification when cli-release job completes and all images have been pushed to registry.odigos.io. Pyxis (red hat) api token is stored in an action secret

Add workflow to submit OpenShift certification automatically

---

.github/dependabot.yml

To keep RHEL images up to date

Configure dependabot for Red Hat UBI image updates

---

Dockerfile.rhel
collector/Dockerfile.rhel
frontend/Dockerfile.rhel
odiglet/Dockerfile.rhel

This switches RHEL Dockerfiles from the main [ubi9 image](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview) to the smaller [ubi9-micro image](https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e?container-tabs=overview)
Size comparison:
```
registry.access.redhat.com/ubi9/ubi 356MB
registry.access.redhat.com/ubi9/ubi-micro 33MB
registry.odigos.io/odigos-ui-ubi9 611MB
registry.odigos.io/odigos-ui-ubi9-micro 207MB
registry.odigos.io/odigos-collector-ubi9 761MB
registry.odigos.io/odigos-collector-ubi9-micro 357MB
registry.odigos.io/odigos-instrumentor-ubi9 567MB
registry.odigos.io/odigos-instrumentor-ubi9-micro 163MB
registry.odigos.io/odigos-odiglet-ubi9 979MB
registry.odigos.io/odigos-odiglet-ubi9-micro …
```

Switch to ubi9-micro images

---

operator/Makefile
operator/bundle/manifests/odigos-operator-odigos-version-55dgk4kht7_v1_configmap.yaml
operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml
operator/config/manager/kustomization.yaml
operator/config/manifests/bases/odigos-operator.clusterserviceversion.yaml

The Operator image is now available at `registry.connect.redhat.com/odigos/odigos-certified-operator-ubi9`, updating the bundle to use this and point to v1.0.159. This will be automated in the future
These changes pushed to the OpenShift operatorhub via https://github.com/redhat-openshift-ecosystem/certified-operators/pull/5295

Update Operator bundle to v1.0.159

---

tests/common/assert/simple-demo-instrumented.yaml
tests/e2e/workload-lifecycle/01-assert-instrumented.yaml

Updating the tests after merging https://github.com/odigos-io/opentelemetry-node/pull/18

fix: use vpid in e2e test assert after agent merge

---

tests/common/apply/install-simple-demo.yaml

The liveness probe generated a lot of not relevant traffic during the e2e test

remove liveness probe from e2e test in simple-demo

---

.github/dependabot.yml

According to the [docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-), `yarn` should be defined with `npm`.

fix: dependabot yarn -> npm

---

cli/cmd/sources.go
docs/cli/odigos_sources.mdx
docs/cli/odigos_sources_disable.mdx
docs/cli/odigos_sources_disable_daemonset.mdx
docs/cli/odigos_sources_disable_deployment.mdx
docs/cli/odigos_sources_disable_namespace.mdx
docs/cli/odigos_sources_disable_statefulset.mdx
docs/cli/odigos_sources_enable.mdx
docs/cli/odigos_sources_enable_daemonset.mdx
docs/cli/odigos_sources_enable_deployment.mdx
docs/cli/odigos_sources_enable_namespace.mdx
docs/cli/odigos_sources_enable_statefulset.mdx
docs/pipeline/sources/delete.mdx
k8sutils/pkg/workload/workloadkinds.go

This adds new commands to the CLI for enabling/disabling Sources: `odigos sources <enable/disable> <type> <name>`
These commands are essentially shorthand for the more explicit (and less user-friendly) `odigos sources create/update` commands.

cli: Add simple enable/disable Source commands

---

instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/otelresource.go

Java and dotnet community were lacking the `k8s.pod.name` resource attribute.
This PR add it to the pod in the webhook.
Currently - the e2e tests assert this value, but it didn't work in practice.
Users who use OSS with java/dotnet, will now see this resource attribute in the generated traces.

fix: introduce k8s.pod.name resource attribute to java and dotnet community

---

cli/cmd/uninstall.go

This PR fixes the failure that occurs during deletion:
```
ERROR Internal error occurred: failed calling webhook "source-mutating-webhook.odigos.io": failed to call webhook: Post "https://odigos-instrumentor.odigos-system.svc:9443/mutate-odigos-io-v1alpha1-source?timeout=10s": service "odigos-instrumentor" not found
exit status 255
```
The error happens because the odigos-instrumentor service is deleted before the mutating webhook, so when attempting to delete a Source, it tries to reach the now non-existent service.
To resolve this, I reordered the deletion steps so that the source mutating and validating webhooks are removed before the actual resource.

fix: deletion error

---

docs/instrumentations/golang/ebpf.mdx

Describes what go "offsets" are, how they work, and the current error that could happen when using bleeding edge dependencies

docs: Add section on Go offsets

---

opampserver/pkg/server/handlers.go
opampserver/pkg/server/server.go

We're currently saving connections even when no heartbeat is detected, which can lead to issues when a process exits abnormally. To address this, we'll delete any saved InstrumentationInstance that lacks a heartbeat. If an error occurs during instrumentation, the eBPF will handle it by marking it as an error.

feat: avoid saving no heartbeat messages

---

.github/workflows/release-artifactregistry.yml

https://goreleaser.com/deprecations/#-rm-dist
```
--rm-dist has been deprecated in favor of --clean.
```

fix: release --rm-dist has been deprecated in favor of --clean

---

collector/exporters/mockdestinationexporter/config.go
collector/exporters/mockdestinationexporter/factory.go
collector/exporters/mockdestinationexporter/go.mod

This PR adds more capabilities to the mock destination exporter in the odigos collector which is used for debug.
It makes the exporter behave like otlp exporter, as well as use the default values that otlp exporter uses.

feat: add queue retry and timeout to mock exporter

---

.github/workflows/publish-modules.yml
Dockerfile
Dockerfile.rhel
Makefile
frontend/Dockerfile
frontend/Dockerfile.rhel
odiglet/Dockerfile
odiglet/Dockerfile.rhel
odiglet/Makefile
operator/Dockerfile

Add ld_flags as build argument to all of our images.
* When building locally, using the Makefile, the images won't get stripped by default. They can be stripped by running:
```
LD_FLAGS="-s -w" TAG=dummy-instrumentor-slim make build-instrumentor
```
* The release CI is updated to strip the images.
* The collector is stripped by default:  https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder#debug-symbols
Some size comparissions:
```
registry.odigos.io/odigos-instrumentor                            dummy-instrumentor-slim   49728c6d5831   2 seconds ago        46.2MB
registry.odigos.io/odigos-instrumentor                            dummy-instrumentor        c3664c33ce34   About a minute ago   66.3MB
registry.odigos.io/odigos-odiglet …
```

Strip binaries to reduce images size

---

common/config/otlphttp_test.go
common/config/utils.go

Following #2673 , this PR fixes the parsing ot otlpHttp endpoint that contains a path in the URL

fix: otlphttp URL with path parse

---

common/mount.go

The mountMethod must be one of `k8s-virtual-device` or `k8s-host-path`, but our API validation only has `virtual-device` or `host-path`. This updates the validation

Fix mount method value enum

---

collector/processors/odigosurltemplateprocessor/README.md
collector/processors/odigosurltemplateprocessor/processor_test.go
collector/processors/odigosurltemplateprocessor/templatize.go

templatize ids that looks like:
- `6f2a9cdeab34f01e` (hex encoded string)
- `INC0032534534` (long number with text)
- `PROCESS_123e4567-e89b-12d3-a456-426614bd4000` (uuid with prefix or suffix)
Not affecting k8s
Less cases of high cardinality when using this processor

feat: enhance url-template processor with more default templatization patterns

---

common/config/debug.go
common/config/testdata/debugexporter.yaml
tests/debug-exporter.yaml

The debug destination currently logs all the telemetry items passing in the pipeline.
For production environments with a lot of data, this can overwhelmed the collector.
This PR adds an option to set lower volume for logging. for example one item per second, protecting us from flooding the logs.
No
New feature in exporter allowing users to debug issues in pipeline

feat: add items per seconds for debug destination

---

autoscaler/controllers/nodecollector/configmap.go
autoscaler/controllers/nodecollector/daemonset.go
autoscaler/controllers/nodecollector/manager.go
autoscaler/controllers/nodecollector/sync.go

When auto scaler reconciled node collector configmap and daemonset, it would use destinations for that.
Fixed:
- Destinations reconciler was not triggering the node reconciler, which caused the cm not to update when a new destination is created that should enable a new signal to be collected.
- exceptions for "span-to-metrics" were calculated from dest which might not be in sync with actual pipeline (this was the case in victoria metrics)
- remove unused parameter `dest` in sync daemonset function.
Added another event filter for the collectors group reconciler which should not have any meaningful overhead.
Fix bug - if there is a tracing destination and one adds a logging destination, it would apply the `filelog` receiver immediately. due to current bug, users restart autoscaler as a …

fix: node collector resolve signals from cluster cg instead of destinations

---

instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/otelresource.go
instrumentor/controllers/instrumentationconfig/source_controller.go
instrumentor/controllers/sourceinstrumentation/common.go
k8sutils/pkg/source/source.go
tests/e2e/workload-lifecycle/02-assert-ic-service-names.yaml
tests/e2e/workload-lifecycle/chainsaw-test.yaml

How we calculate the service name to use for each config?
- if the user set this in workload source object - use it
- otherwise - use the workload name as default ("coupon", "membership", etc)
This PR moves this logic from the pods webhooik to the reconcilers, insuring that the right value is always updated in the existing field and is never empty.
Then we can set it only once, and don't need to resolve it downstream in multiple consumers.
Reduce work in webhook, and do it only few times in controller instead of again and again for each pod.
This removes a `Get` request to the cache during webhook which is a good improvement 🎉
Internal refactor

refactor: resolve service name in controller instead of webhook

---

instrumentor/controllers/agentenabled/sync.go

Get rid of errors in instruomentor logs that looks like:
```
2025-04-18T13:45:52Z    ERROR    Reconciler error    {"controller": "agentenabled-instrumentationconfig", "controllerGroup": "odigos.io", "controllerKind": "InstrumentationConfig", "InstrumentationConfig": {"name":"deployment-demo-php","namespace":"demo-php"}, "namespace": "demo-php", "name": "deployment-demo-php", "reconcileID": "93ec2c15-8c72-4e32-896d-60ba0a5d3241", "error": "Operation cannot be fulfilled on instrumentationconfigs.odigos.io \"deployment-demo-php\": the object has been modified; please apply your changes to the latest version and try again"}           ││ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler …
```

fix: handle update error on agent enable controller

---

.vscode/launch.json
cli/cmd/resources/odiglet.go

This PR fixes a bug in cli upgrade. When the newly introduced `odigos-go-offsets` already exists, the cli upgrade would try to apply the object that is returned from the k8s api, but this is not supported (missing kind, `ERROR metadata.managedFields must be nil` etc).
To fix it, I always create the configmap in the supported manner, and just copy the content.
This does not fail in tests, since the test runs cli-upgrade from a version which does not contain offsets file, thus it's a create not an update to existing object.
fix a bug in how cli upgrade is applying changes to an existing cm
no

fix: go-offsets reapply

---

autoscaler/controllers/nodecollector/configmap.go

Add or update existing `k8sattributes` processor to also collect workload names attributes (`k8s.deployment.name` etc).
Also add a processor to transform these resource attributes to `service.name` if found.
No changes in k8s (other than adding a new consumer to `k8sattributes` processor which we want).
Each logs user will now automatically get workload names attributes and `service.name` if possible.

feat: auto add logs processors to the node collector pipeline

---

destinations/data/otlp.yaml
destinations/data/otlphttp.yaml
docs/backends/otlphttp.mdx

Add the test connection button for the OTLP HTTP and OTLP gRPC destinations
manually tested with both destinations

add test connection for OTLP gRPC and OTLP HTTP destinations

---

autoscaler/controllers/nodecollector/daemonset.go
tests/common/assert/pipeline-ready.yaml

Odigos reads logs from k8s node fs in `/var/log`. in some systems, this path is a symlink to `/mnt/var/log`, so we need to mount this as well for the logs collection to work.
This will not cover all possible cases, but the hope is that `/mnt/var/log` is common enough to cover most non-trivial cases.

fix: mount /mnt/var/log into node collector

---

agents/python/setup.py

Changed how python instrumentation are overloaded, version bumped the python agent

Version bump odigos-opentelemetry-python

---

tests/e2e/helm-chart/chainsaw-test.yaml

Been seeing failures like [this one](https://github.com/odigos-io/odigos/actions/runs/14621198252/job/41026869724?pr=2764) where the odiglet is still pending/initializing. Maybe there is something actually blocking it, but possibly it just needs a little more time than the default which appears to be 30s. Opening this as a test to see

e2e: increase Odigos installed assertion timeout

---

operator/DEVELOPMENT.md
operator/Makefile
operator/bundle/manifests/odigos-operator-odigos-version-t9g2c28b4f_v1_configmap.yaml
operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
operator/config/manifests/bases/odigos-operator.clusterserviceversion.yaml

This updates the operator to the latest v1.0.177 images and adds more documentation on releasing the operator

Update Operator to v1.0.177

---

instrumentor/internal/webhook_env_injector/webhook_env_injector.go
tests/e2e/env-injection/01-assert-apps-installed.yaml
tests/e2e/env-injection/01-assert-env-vars.yaml
tests/e2e/env-injection/01-assert-runtime-detected.yaml
tests/e2e/env-injection/01-install-test-apps.yaml

Following https://github.com/odigos-io/odigos/pull/2667, we append our value only to one env var if we detect a user defined value. That PR also covers the case where the env var (for example JAVA_OPTS) is declared by the user and have an empty value. For that case, we'll add our value only to the JAVA_OPTS. Most (if not all) the JDKs don't looks for the JAVA_OPTS env var for agent injecting - hence this results in the agent not being injected.
We should completely remove JAVA_OPTS in a future PR, this is done as a quick fix.
- [ v ] Changes how Odigos interacts with Kubernetes
Only the described case above will affect the pod webhook operation and will result in different pod spec.

Handle empty JAVA env vars as if they are not defined

---

.github/workflows/publish-modules.yml

When we push a new tag for release, and the offset PR in enterprise repo is not merge, the release stops but there isn't any message in slack for that.
This PR adds a success / error messages so we can be aware + a link to the offsets PR for quick reaction with minimal toll.
It's mostly chatGPT and not trivial to test, so we need to keep an eye in the next few releases.
We also need to think if it's easy to re-trigger the release in OSS after the offsets PR is merged (in case one stopped due to missing offsets) but that's a task for future work.

ci: notify slack on success / failure of offset check pre release

---

collector/processors/odigosurltemplateprocessor/README.md
collector/processors/odigosurltemplateprocessor/processor_test.go
collector/processors/odigosurltemplateprocessor/templatize.go

There is a templatization rule that automatically templatize path segments which are numbers (only digits).
This PR extends it to cover digits or special character, which is targeted to also match things like `123_456` which are currently not templated.
No
Cover more id cases by default

feat: make every path segment without letters template

---

collector/processors/odigosurltemplateprocessor/README.md
collector/processors/odigosurltemplateprocessor/config.go
collector/processors/odigosurltemplateprocessor/filtermatcher.go
collector/processors/odigosurltemplateprocessor/processor.go
collector/processors/odigosurltemplateprocessor/processor_test.go
collector/processors/odigosurltemplateprocessor/templatize.go

If user set their our custom ids for url templatization, they can now also give the template name (instead of it being fallback to "id")
No
More configuration options

feat: urltmeplate processor allow to set template name for customid

---

agents/python/setup.py

Bump python agent version to v1.0.43 it's including a fix for sqlalchemy engine issue.

chore: bump python agent version to v1.0.43

---

instrumentor/controllers/agentenabled/podswebhook/env.go
instrumentor/controllers/agentenabled/podswebhook/otelresource.go
instrumentor/internal/webhook_env_injector/webhook_env_injector.go

Bug caught by nightly tests;
The 3 `OTEL_<SIGNAL>_EXPORTER` envs were injected twice due to no checks on exiting envs.
This PR makes sure the envs are checked before being injected.
---
Output from nightly with double envs:
```
Error: some tests failed
l.go:52: | 00:26:55 | multi-apps | Simple-demo instrumented after destination added | ASSERT    | ERROR | v1/Pod @ default/*
=== ERROR
----------------------------------------
v1/Pod/default/currency-695979478b-t6xb9
----------------------------------------
* spec.containers[0].(env[?name == 'OTEL_LOGS_EXPORTER']): Invalid value: []interface {}{map[string]interface {}{"name":"OTEL_LOGS_EXPORTER", "value":"none"}, map[string]interface {}{"name":"OTEL_LOGS_EXPORTER", "value":"none"}}: lengths of slices don't match
* …
```

fix: double env injections

---

helm/odigos/templates/cleanup/cleanup-job.yaml
helm/odigos/values.yaml

Fix bug, in which the image used for the cleanup hook could have the wrong name if the user has set `values.imagePrefix`.
Use the same helm template function we use for all other images in the templates.

fix: use the correct cli image for helm cleanup hook

---

odiglet/odiglet.go
odiglet/pkg/instrumentation/fs/agents.go
operator/DEVELOPMENT.md

SELinux doesn't seem to consistently handle re-applying existing rules with `semanage`. It can sometimes result in an error that currently prevents the Odiglet from starting up. This PR does 2 things for RHEL hosts:
1. First check if an selinux rule exists for Odigos. If it does, don't both trying to re-apply
2. If we do hit some (unknown) error anyway, log the error and don't crash the Odiglet. This means we can still start up as a best effort in error cases, with the tradeoff that Odigos may not work if there was a different issue.

openshift: Check if SEManage rule already exists

---

agents/python/setup.py
docs/instrumentations/python/native.mdx

Bumping Odigos python agent version to v1.0.45 which include two additional instrumentations.
Also, adjusted the documentation and mention that these two libraries are now supported

Bump odigos py agent

---

tests/common/queries/span-attributes.yaml

Nightly build images with the latest commit hash as the version.
in the span-attributes.yaml we were checking explicitly version is e2e-test.
I think better to keep tagging the nightly images with hash so we will know what is the latest commit tested.

chore: remove check for version

---

docs/permissions.mdx
helm/odigos/templates/cleanup/cleanup-clusterrole.yaml

Following #2784, adding the required permissions for sources to the cleanup job in helm

fix: add sources premission for helm cleanup job

---

.github/workflows/generated-docs.yaml
docs/api-reference/operator.odigos.io.v1alpha1.mdx

In several PRs, we are removing and re-adding the Operator CRD docs, see:
* https://github.com/odigos-io/odigos/pull/2731/files (added)
* https://github.com/odigos-io/odigos/pull/2707/files (deleted)
* https://github.com/odigos-io/odigos/pull/2783/files (added)
* https://github.com/odigos-io/odigos/pull/2783/files (deleted)
This tries to update the CRD docgen check to make sure the local go workspace in the action is actually verifying all docs are present

docs: Update go workspace in CRD docgen

---

common/config/otlphttp.go
destinations/data/otlp.yaml
destinations/data/otlphttp.yaml
docs/backends/otlphttp.mdx

This adds the same TLS settings for otlpgrpc (https://github.com/odigos-io/odigos/pull/2763) to the otlphttp exporter

otlphttp: Support TLS settings

---

.github/workflows/publish-modules.yml

Similar to https://github.com/odigos-io/odigos/pull/2680, this adds a pre-release check for open enterprise dependency sync PRs.
Currently, the release flow will create a release PR in the enterprise repo that is effectively a dependency sync. However, if there are currently failing tests with the current dependency sync, it would be good to catch these before we start a release flow instead of having to debug it mid release.
Making this a separate job so it can depend on the verify-offsets check, which itself will trigger a dependency bump if there are offsets changes to be merged

Add dependencies-syncer-bot PR check to release workflow

---

helm/odigos/templates/odigos-config-cm.yaml
helm/odigos/values.yaml

If user did not set `mountMethod` in helm values, do not default it in helm.
This is to accurately differentiate between user did not set any value, and user set a value to be the `k8s-virtual-device` (default).
odigos profile will only override the value if it's empty (assuming that if a user specified a value it will be used and not the profile), so this change allows us use profiles for mount method in helm correctly

fix(helm): do not default mountMethod to allow profile override

---

odiglet/odiglet.go

This was removed as a breakglass effort to allow recoverable errors from SEManage to continue execution in https://github.com/odigos-io/odigos/pull/2805. Further testing showed that the changes from #2805 are sufficient to prevent these recoverable errors. Reverting the `os.Exit` call to prevent odiglet from starting in other error cases

odiglet/openshift: Re-add os.Exit when OpenShift setup fails

---

collector/processors/odigosurltemplateprocessor/README.md
collector/processors/odigosurltemplateprocessor/processor_test.go
collector/processors/odigosurltemplateprocessor/templatize.go

This PR address minor improvments to url templatization following user feedbacks:
- support hex encoded strings with capital letters.
- fix configuration example in the README
- minor text improvments in README
- add warning at beginning of README about high cardinality 
Add unit test

feat: allow hexencoded url template path with captical letters

---

agents/python/setup.py

This Odigos python include fix for urllib3 missing attributes in client spans.

chore: bump python version to 0.48

---

odiglet/pkg/ebpf/settings_getter.go
odiglet/pkg/kube/utils/utils.go
tests/common/queries/resource-attributes.yaml

Adding the following resource attributes to the eBPF instrumentations:
* `k8s.container.name`
* `process.command`
* `process.executable.path`
* `process.pid`
* `process.vpid`
Adding the container name allows the `k8sAttributesResolver` to add more container attributes about the container image and tag.
Updated e2e query to assert that the container name is present in all the spans.

feat: add container and process resource attributes to eBPF instrumentations

---

collector/processors/odigosurltemplateprocessor/README.md
collector/processors/odigosurltemplateprocessor/processor_test.go
collector/processors/odigosurltemplateprocessor/templatize.go

If a url path contains unicode replacement character, assume it's not static path segment and templtaize it with urltemplatization processor. following request from user
No
Fix user issue for auto templatization behavior

feat: url template unicode replacement character

---

frontend/graph/conversions.go
frontend/graph/schema.resolvers.go

Our UI currently only tracks InstrumentationConfig conditions, stopping at `rollout triggered successfully` and showing `Everything Successful` if we reach that point
But in reality, the rollout could have failed on the Workload's end (due to resource quotas, scheduling issues, etc). This is confusing to the user because Odigos says everything should be instrumented and working.
This tries to grab the Workload's conditions and shows them alongside the instrumentation. This will be much more convenient than trying to manually debug the workload with kubectl.
The alternative would be adding Workload conditions to Sources/InstrumentationConfigs in the backend. This would require a controller to watch for updates to every workload in the cluster, which would be very expensive and unnecessary, …

ui: Add Workload Conditions to Source view

---

cli/cmd/resources/instrumentor.go
helm/odigos/templates/instrumentor/webhooks.yaml

We should really be rejecting Sources that fail the Validating webhook, since we rely on a lot of assumptions from it (like the format of labels etc)

instrumentor: Set ignorePolicy: Fail on Source ValidatingWebhook

---

CONTRIBUTING.md
docs/mint.json

Fixed typos:
•  "Contibution" -> "Contribution" in mint.json
•  "When submitt" -> "When submitting a pull request" in CONTRIBUTING.md

Docs: Fix typo in group name and PR guidelines

---

distros/yamls/php-community.yaml
odiglet/Dockerfile
odiglet/Dockerfile.rhel
odiglet/debug.Dockerfile
odiglet/pkg/instrumentation/fs/agents.go
tests/common/assert/simple-demo-instrumented-full.yaml
tests/e2e/cli-upgrade/chainsaw-test.yaml

The PHP agents had the OTel SDK built & registered twice, which caused issues such as recording spans from the OTel exporter itself.
This version kills the custom built SDK in favor of the auto-built SDK.

feat: update PHP agent version to v0.1.21

---

cli/cmd/config.go
common/consts/consts.go
common/envOverwrite/overwriter.go
common/odigos_config.go
distros/yamls/java-community.yaml
docs/cli/odigos_config.mdx
helm/odigos/templates/odigos-config-cm.yaml
helm/odigos/values.yaml
instrumentor/internal/webhook_env_injector/webhook_env_injector.go
profiles/aggregators/kratos.go
profiles/allprofiles.go
profiles/instrumentation/envvar_injection.go
tests/common/assert/simple-demo-instrumented-full.yaml
tests/e2e/env-injection/01-assert-apps-installed.yaml
tests/e2e/env-injection/01-assert-env-vars.yaml
tests/e2e/env-injection/01-assert-runtime-detected.yaml
tests/e2e/env-injection/01-install-test-apps.yaml
tests/e2e/env-injection/02-assert-env-vars.yaml
tests/e2e/env-injection/03-assert-env-vars.yaml
tests/e2e/workload-lifecycle/01-assert-runtime-detected.yaml

Complete the transition started at #2776 - and remove any modification to the JAVA_OPTS env var.
JAVA_OPTS is used by tools like catalina/tomact that are usually launched using a big bash script. This env var is usually used for configuring such tools, but it has not affect on the JVM itself.
Following https://github.com/odigos-io/odigos/pull/2667, when a user app is using JAVA_OPTS we'll end up adding our value there which will not add our agent.
After this PR only JAVA_TOOL_OPTIONS will be used.
Users that experience the described bug will need to upgrade the odigos version, and do a rollout to their workloads if they are in a Crashloop state, or re-instrument them.
Previous version of odigos can use the `avoid-java-opts` profile which is being removed here.

fix: remove use of JAVA_OPTS for instrumentation

---

common/consts/consts.go
frontend/webapp/package.json
frontend/webapp/yarn.lock
instrumentor/controllers/sources_webhooks.go
tests/e2e/webhooks/defaulting-01-assert-source-without-labels.yaml

This PR adds a default data-stream label to Source CRDs, and validates the existence of a label.

feat: add default data-stream label & data-stream validation in sources webhook

---

common/consts/consts.go
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/mount.go
instrumentor/internal/webhook_env_injector/webhook_env_injector.go
odiglet/Dockerfile
odiglet/Dockerfile.rhel
odiglet/debug.Dockerfile
profiles/aggregators/kratos.go
tests/e2e/env-injection/02-assert-env-vars.yaml
tests/e2e/env-injection/03-assert-env-vars.yaml

* Change the location of the loader from `/var/odigos/loader.so` to `/var/odigos/loader/loader.so` - this will allow us to make more precise mounts when using the host path method for mounting.
* Add `loader-fallback-to-pod-manifest` to kratos profils.

add loader dir to be used by host path mount when needed

---

api/k8sconsts/odiglet.go
cli/cmd/resources/odiglet.go
helm/odigos/templates/odiglet/daemonset.yaml
helm/odigos/templates/odiglet/local-service.yaml
instrumentor/controllers/agentenabled/podswebhook/env.go
k8sutils/pkg/service/service.go
odiglet/pkg/instrumentation/instrumentlang/nodejs.go
odiglet/pkg/instrumentation/instrumentlang/python.go
tests/common/assert/odigos-installed.yaml
tests/common/assert/odigos-upgraded.yaml
tests/common/assert/simple-demo-instrumented-full.yaml

Followup to #2458 - adding similar service to `Odiglet` - this allows us to run without `hostNetwork` for k8s versions >= 1.26.
For version < 1.26 the same behavior is kept.

use internalTrafficPolicy for opAmp to allow removing hostNetwork from odiglet

---

api/odigos/v1alpha1/instrumentationconfig_types.go
frontend/services/utils.go

This adds the k8s workload condition reason for `FailedCreate` to the disabled status conditions list in the UI
The PR https://github.com/odigos-io/odigos/pull/2871 originally added this and other failed workload conditions so it would appear as a failure, which can be confusing for users (thinking that Odigos itself has failed when in reality it is the workload rollout). This softens that appearance
Note that before we were making this condition show as an error by looking at its _type_ (`ReplicaFailure`), but now we are using its _reason_ (`FailedCreate`) which aligns with the disabled conditions we are already checking.
In the future we may want to expand this, as well as check for _types_ instead of just _reason_s, but this is a start
For reference, see the following failing …

ui: Show bad Workload conditions as disabled instead of error

---

frontend/graph/schema.resolvers.go
frontend/services/destinations.go
frontend/services/instrumentationrule.go
frontend/services/sources.go
frontend/services/utils.go
k8sutils/pkg/feature/feature.go

see https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/4420-retry-generate-name/README.md
> But there is a problem with name conflicts. There is a 50% chance of hitting a conflict before generating even 5000 names, and a 0.1% chance at only 500 names!
> 
> Today a HTTP 409 respose returned to the client if a name conflict happens. It is possible for clients to detect the error and retry, but we've seen that most clients don't realize to do this and hit this problem in production.
It appears that pre k8s 1.32, every call to create a new resource in k8s with `GenerateName` can fail with this error reported from one of our users:
This PR fixes this bug by retrying the Create operation if we got back conflict and the k8s version is < 1.32.
With k8s >= 1.32, the api …

fix(frontend): retry create object with generated name on conflict

---

instrumentor/controllers/agentenabled/sync.go

If a user configures a container as an ignored container, and the language of this container is not supported, we should set its status to "Ignored Container" to avoid confusing users in the UI.

chore: set agent enabled as container ignored over unknown language if both happens

---

docs/setup/installation.mdx
helm/odigos-central/templates/_helpers.tpl
helm/odigos-central/templates/centralbackend/central-backend-service.yaml
helm/odigos-central/templates/centralbackend/deployment.yaml
helm/odigos-central/templates/centralui/deployment.yaml
helm/odigos-central/templates/redis/redis-service.yaml
helm/odigos-central/templates/redis/redis.yaml
helm/odigos-central/values.yaml
helm/odigos/templates/_helpers.tpl
helm/odigos/templates/centralproxy/deployment.yaml
helm/odigos/templates/centralproxy/role.yaml
helm/odigos/templates/centralproxy/rolebinding.yaml
helm/odigos/templates/centralproxy/serviceaccount.yaml
helm/odigos/templates/instrumentor/deployment.yaml
helm/odigos/templates/odiglet/daemonset.yaml
helm/odigos/templates/odigos-deployment.yaml
helm/odigos/values.yaml

Allow installing odigos pro using an existing secret

Check if odigos-pro secret exists before installing helm chart

---

api/odigos/v1alpha1/source_types.go
instrumentor/controllers/workloadmigrations/controllers.go
k8sutils/pkg/source/source.go

This function can be used for any PodWorkload and it is not really need to get a  generic `client.Object`.
We use all over Odigos the PodWorkload object.

chore: generalise GetSource func

---

api/k8sconsts/source.go
instrumentor/controllers/sourceinstrumentation/common.go
instrumentor/controllers/sourceinstrumentation/instrumentationconfig_controller.go
k8sutils/pkg/source/source.go

In the Datastreams world we agreed to use the instrumenationConfig as the single point of truth for building the configuration and also for the UI to consume.
This PR ensure that this data will reconcile into the  instrumenationConfig for each workload with the workload source and also the namespace source.

Reconcile sources to instrumentationconfig

---

cli/cmd/sources.go
instrumentor/controllers/sourceinstrumentation/instrumentationconfig_controller.go
k8sutils/pkg/utils/version.go
k8sutils/pkg/workload/workload.go
k8sutils/pkg/workload/workloadkinds.go

Support for cronJobs in k8s version 1.20

---

.github/workflows/check-rbac-changes.yml
docs/permissions.mdx
operator/Makefile
operator/bundle/manifests/odigos-operator-odigos-version-kfkk8hb6bf_v1_configmap.yaml
operator/bundle/manifests/odigos-operator.clusterserviceversion.yaml
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
operator/config/manifests/bases/odigos-operator.clusterserviceversion.yaml
operator/config/rbac/role.yaml
operator/internal/controller/odigos_controller.go

This updates the operator to 1.0.198 along with changes to permissions that are necessary for it to grant those permissions to components.
This also adds a workflow to make sure that when components are granted new permissions, the operator's RBAC is updated as well.
Openshift release PR: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/5944

operator: update to v1.0.198

---

cli/cmd/pro.go
docs/cli/odigos_pro_update-offsets.mdx

This allows downloading a Go offsets file locally and using the local file (ideally for users where the cluster itself may not have direct internet access)

cli: add  `download-file` and `from-file` flags to update-offsets

---

helm/odigos/templates/_helpers.tpl
helm/odigos/templates/odiglet/daemonset.yaml
helm/odigos/templates/odiglet/local-service.yaml

In some environments (e.g., EKS), the Kubernetes version string can appear in a format like v1.30.13-eks-5d4a308.
This non-standard format causes semverCompare to fail when attempting to compare versions.
To address this, I’ve implemented a helper function that sanitizes the version string, ensuring the comparison logic operates correctly.

chore: semvercompare function fix

---

odiglet/Dockerfile

For the nodejs agent , we currently run `yarn install` and copy the generated `node_modules` into the odiglet.
This brings in all the dev dependencies, which includes typescript with 21 MB on disk.
After this change, we install only production dependencies, and can reduce 21 MB from the folder size we need to embed in odiglet image, and we need to use on the host.

chore: remove unused deps from nodejs agent node_modules

---

distros/yamls/nodejs-community.yaml

When instrumenting a nodejs application, if OpAMP is unable to connect, then we use default config. but this config lacks important attributes like `k8s.namespace.name`, `k8s.deployment.name` and `service.name`.
At the moment, the spans from nodejs when opamp cannot start looks like this:
and missing k8s attributes. This PR adds these k8s attributes as environment variable which solves the issue

fix: set k8s attributes as nodejs agent env to show when opamp is down

---

instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/env.go

A small refactor.
In the pods webhook, we are currentlyr reading the enabled signals from the collectors group.
Now that this info is found on the containers array of instrumentation config spec, we can use it from there, and avoid a cache call from webhook to get this.

refactor: pods webhook read signals from ic

---

common/config/genericotlp.go
common/config/otlphttp.go
common/config/otlphttp_test.go
destinations/data/otlp.yaml
destinations/data/otlphttp.yaml
docs/backends/otlp.mdx
docs/backends/otlphttp.mdx

The otlp and otlp-http destination requires few oauth2 fields.
If user want an otlp destination without these fields, the UI fails to add the new destination since those required fields are empty.
Fix: make the fields optional and check during reconcile
No
user can add new otlp and otlphttp destinations after the fix

fix: otlp oauth required fields prevent adding non-auth dest

---

api/odigos/v1alpha1/instrumentationconfig_types.go
instrumentor/controllers/agentenabled/sync.go

Since https://github.com/odigos-io/odigos/pull/2738 , the cluster collectors group is generated even if there are no destinations.
That means that once sources are added, the datacollection will become ready and we will inject agent and rollout.
This is problematic because:
- Some distributions consumes the enabled signals as env vars  at pod creation time, and currently we are rollouting too early, creating pods with all signals disabled which are not being updated later once a destination is added.
- We are creating noise in the cluster, doing rollouts before it's relevant.
- There is no indication to the user that the agent is injected but all signals are disabled, thus they should not expect any telemetry
Fix: add a new condition for that, and test it in agentenabled controller of …

fix: inject agent only if signals are enabled

---

instrumentor/controllers/agentenabled/instrumentationrule_controller.go
instrumentor/controllers/agentenabled/manager.go
instrumentor/controllers/utils/predicates/instrumentation_rule.go

Fix 2 bugs in the triggering of agent injection from instrumentation rules changes:
1. the predicate only checks for the deprecated "OtelSdk" rule, and not checking for the new "OtelDistros" rule. this is fixed to check both
2. the reconciler only trigger recalculate if the rule is not `nil`, but it need to cleanup any possible modification even if the rule is nil if before the update it was not nil.
More reconciles invocation to catch events that we should have handled and missed before.
If any user is using the otelDistro rule (which is not yet in the UI) then his changes will take effect where before they did not immediately did.

fix(instrumentor): predicate for agent injection on rules check distros

---

common/lang_detection.go
distros/distro/oteldistribution.go
distros/oteldistributions.go
distros/yamls/php-community.yaml
distros/yamls/ruby-community.yaml
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/podswebhook/env.go
instrumentor/controllers/agentenabled/podswebhook/otelresource.go
instrumentor/controllers/agentenabled/sync.go

Php and Ruby requires the runtime version as "Major.Minor" (`8.3`) to inject into environment variables.
At the moment, we read and parse the value in pods webhook, but this is not ideal for the following reasons:
- More work in webhook, vs pre-calculate at reconcile time and having the value ready at webhook time.
- No error checking - in webhook, we need to parse versions but do not check for errors (like if the version is updated at runtime detection and no longer valid)
- Race conditions - we read plain values from runtime detection in webhook, before they are being reconciled and potentially modify the agent config.
This PR migrate the php and ruby to pass distro parameter in the containers array for `RUNTIME_VERSION_MAJOR_MINOR`:
- process and parse the runtime detection version in …

refactor: runtime version as distro parameter

---

opampserver/pkg/sdkconfig/instrumentationconfigs_controller.go

Opamp server had no predicate on the instrumentation configs it was processing.
This caused us to reconcile too much, where we can limit the number of events like we do in other places.
This PR adds trivial filter which should already reduce quite a lot of events:
- generation change - filter condition updates and runtime details detections
The filter can be refined further, but I want to start with these and improve the filtering as I refactor the mechanism later on.
Odiglet will reconcile less - less CPU. no effect on API server.
Internal refactor

refactor(opamp): add ic predicates to reduce events

---

common/config/genericotlp.go
common/config/genericotlp_test.go
common/config/otlphttp.go
common/config/otlphttp_test.go

In https://github.com/odigos-io/odigos/pull/3069, the tls config was moved to only be set if configured by a user explicitly or through oauth
However, this means that disabling TLS in these destinations does not set `tls.insecure: true`. This updates both destinations to fix the regression
This can cause errors like:
```
rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake
```
or
```
connection error: desc = "transport: Error while dialing: dial tcp 10.96.133.107:4317: connect: connection refused"
```

otlp destinations: Set tls insecure:true if TLS is not enabled

---

collector/processors/odigossqldboperationprocessor/processor.go

We have a processor that heuristically determines the SQL operation name by extracting the first word from the db.query.text. Once identified, we append this operation name to the span names to avoid scenarios where users see spans labeled only as "DB", which can be ambiguous.

chore: adding the operation name fo the span name if missing

---

common/pipelinegen/config_builder.go

Once creating a Datadog with combination of traces + metrics, we're creating connector to send metrics based on the traces to the metrics destination.
in the Datastream implementation we lack support for this and this PR fixes it.

chore: fix datadog special senario

---

.github/workflows/publish-modules.yml

This allows maintainers to add the `release-blocker` label to a PR to prevent a release from being published without that PR.
Other maintainers can always remove the `release-blocker` label if the release is urgent and doesn't depend on that PR

Add release-blockers option to label PRs for targeted release

---

.github/workflows/create-release-pr.yml
scripts/create-release-pr.sh

Add the token to avoid these errors in CI:
```
* [new branch]        release/v1.0.206 -> release/v1.0.206
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```

ci: run create release PR with the relevant token

---

Makefile

At some point, the `--push` flag was removed from `make push-image` (probably by me). This adds it back safeguarded around a `PUSH_IMAGE` env var to make sure you really want to push.
This also makes it easier to push to staging/sandbox by setting `STAGING_ORG=true`. So for example, now we can run
```
PUSH_IMAGE=true STAGING_ORG=true TAG=test make push-collector
```
This will `buildx` the multi-arch collector image and push it to Artifact Registry where it can be pulled from `staging-registry.odigos.io`

Update make push-image commands for staging

---

cli/cmd/resources/instrumentor.go
docs/permissions.mdx
helm/odigos/templates/instrumentor/role.yaml
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/manager.go

This is a safeguard, so if odiglet is deleted or have no ready replicas, the webhook will avoid to inject instrumentation into the pod.
While unlikely, if odiglet is deleted or all replicas are not ready, then the pods webhook might add the instrumentation device or the affinity and cause the pod to be unscheduled (odiglet is currently required for the pod to start on a node).
This can help us increase stability in some edge cases.
pods webhook in instrumentor now need to query daemonset, and it will skip mutating the pod if odiglet is "not found"
Not expected

fix: do not inject instrumentation to pod if odiglet is not ready

---

procdiscovery/pkg/inspectors/golang/golang.go

While testing the minimum golang version odigos supports (`v1.17.0`) I noticed that there is no language detection for this service. the odiglet logs has:
```
{"level":"error","ts":1752332183.664659,"caller":"controller/controller.go:347","msg":"Reconciler error","controller":"Odiglet-RuntimeDetails-Pods","controllerGroup":"","controllerKind":"Pod","Pod":{"name":"versionminimum-9f4cb6578-cd4f8","namespace":"golang-httpserver"},"namespace":"golang-httpserver","name":"versionminimum-9f4cb6578-cd4f8","reconcileID":"b0be3579-19e2-4ed0-85a4-5c88496d8dc9","error":"panic: runtime error: index out of range [1] with length 0 [recovered]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/ …
```

fix: check length of golang regex result before accessing

---

.github/workflows/generated-docs.yaml

The destination docs generation script applies a formatting to the `mint.json` file.
Sometimes when we manually add doc pages (for example PR #3167), the CI fails due to formatting change (see job https://github.com/odigos-io/odigos/actions/runs/16250264278/job/45878946842?pr=3167), this change is not relevant to the actual generation of docs, and should not be a reason to fail the CI.
This PR makes sure we ignore the file in the git status check.

ci: ignore mint.json from the git status check

---

.github/workflows/build.yaml
.github/workflows/e2e.yaml

In CI tests - load images directly to kink instead of loading them to ci node and then `docker-load` from the local registry to kind. saves ~30sec in each test run

ci: nit cleanups

---

.github/workflows/publish-modules.yml

Add missing permissions to publish packages from github actions

ci: add permissions to publish packages from workflow

---

rc/README.md
rc/index.yaml

Adding a directory to our gh-pages branch to server release candidate charts

Initial setup of release candidate subdirectory

---

.goreleaser.yaml

This PR fixes a bug in CI where we publish to brew and use owner "keyval-dev".
It causes error in ci: "homebrew formula: could not get default branch: GET https://api.github.com/repos/keyval-dev/homebrew-odigos-cli-rc: 404 Not Found []"
Seems that the new repo is created after "keyval-dev" is deprecated, and thus it should be changed to work

ci: fix owner for homebrew

---

frontend/webapp/.prettierrc
frontend/webapp/components/lib-imports/setup-header.tsx
frontend/webapp/package.json
frontend/webapp/yarn.lock

* add supported languages for instrumentation rules ([#243](https://github.com/odigos-io/ui-kit/issues/243)) ([534e196](https://github.com/odigos-io/ui-kit/commit/534e196f9118bcdff5a72f05e5e42e0d5c841a6b))
* enhance useGenericForm hook with isFormDirty state ([#240](https://github.com/odigos-io/ui-kit/issues/240)) ([3cc2f2b](https://github.com/odigos-io/ui-kit/commit/3cc2f2ba0092ac8ea7652c977c564221a7c714ab))
* filter by running instances for source selection form ([#244](https://github.com/odigos-io/ui-kit/issues/244)) ([1122570](https://github.com/odigos-io/ui-kit/commit/1122570267ecb3158a944c3215d2adceea229e08))
* dropdown values for destination during onboarding ([#242](https://github.com/odigos-io/ui-kit/issues/242)) ([bd528dd](https://github.com/odigos-io/ui-kit/commit/bd528ddb06cda7 …

chore: bump UI-Kit to v0.0.58

---

api/k8sconsts/odigoscentral.go
cli/cmd/resources/centralodigos/centralbackend.go

This commit introduces a ServiceAccount, Role, and RoleBinding for the central backend, which fixes the following error:
```json
{
"time": "2025-07-16T17:24:24.594592007Z",
"level": "ERROR",
"msg": "Failed to get admin credentials",
"error": "failed to get secret data: failed to get secret keycloak-admin-credentials in namespace odigos-central: secrets \"keycloak-admin-credentials\" is forbidden: User \"system:serviceaccount:odigos-central:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"odigos-central\""
}
```

feat: add Kubernetes RBAC resources for Central Backend

---

.github/workflows/release-artifactregistry.yml

If someone pushed to main after we created the tag and before the release cli workflow is initiated, we get errors from goreleaser saying:
```
• git state                                      commit=f2229e3595e7ca3a2b8a6ea2cf8f1fc448a840fa branch=main current_tag=api/v1.0.213-rc1 previous_tag=v1.0.213-rc0 dirty=false
git tag api/v1.0.213-rc1 was not made against commit f2229e3595e7ca3a2b8a6ea2cf8f1fc448a840fa
```
This PR makes sure we are checked out to the right tag before releasing

ci: checkout to the relevant tag before release

---

.github/workflows/full-build.yaml

Add a workflow to build all the services, with both rhel and regular dockerfiles, and for both arm64 and amd64.
We are currently doing this on every PR to main, and I want to do it for the release-candidate PRs as well.
Later on, we can consider to run the full builds only on release PRs, and avoid them on regular merges to main, as they take a lot of time to run, cost a lot of money, and give very little value.

ci: add full build for release candidate prs

---

.github/workflows/create-release-candidate.yml
.github/workflows/full-build.yaml

For the release branch, instead of naming it "release-v1.0.x", use "releases/v1.0.x".
Update in few places

ci: use slash for release branches names

---

.github/workflows/full-build.yaml

At the moment, the `full-build` workflow isn't running for release candidate PRs, probably since this PR has no changed files.
This should fix the issue and always run the workflow even if this PR has no changes

ci: allow empty prs to trigger build

---

distros/yamls/golang-community.yaml
docs/instrumentations/golang/ebpf.mdx

our min version for golang-community distro is set to `1.17` but the upstream is `1.19`: 
https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/COMPATIBILITY.md
When I tested it locally, versions 1.17 and 1.18 fails with the following offsets error:
This PR aligns our minimum version to the actual value we support.

fix: set golangg-community distro min version to 1.19

---

instrumentor/controllers/manager.go
instrumentor/controllers/sourceinstrumentation/manager.go
instrumentor/controllers/sourceinstrumentation/suite_test.go
instrumentor/controllers/sourceinstrumentation/workload_controllers.go
instrumentor/instrumentor.go

There are reconcilers for each workload type under instrumentor "sourceinstrumentaiton" controllers, but CronJob is missing.
Before this PR, if a cronjob was removed and added, there was no instrumentation config generated for it. This PR fixes the bug by applying the same sync to CronJob as we do for other types.
~~- [ ] Introduces additional calls to the API Server (potential performance impact)~~
~~- [ ] Modifies Odigos manifests (addressed in both CLI and Helm)~~ 
~~- [ ] Changes RBAC permissions~~ all RBAC permissions are already set correctly regarldless of this change
Fix edge case bug in very rare scenario

fix: reconcile cronjob in instrumentor source creation

---

.github/workflows/release.yml

Now that we have both release-candidate and stable release, and they can both point to the commit, goreleaser get's confused and picks the wrong one.
```
• failed to upload artifact, will retry        try=1 artifact=checksums.txt error=POST https://uploads.github.com/repos/odigos-io/odigos/releases/234954876/assets?name=checksums.txt: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
scm releases: failed to publish artifacts: failed to upload cli_1.0.213-rc4_linux_amd64.tar.gz after 1 tries: POST https://uploads.github.com/repos/odigos-io/odigos/releases/234954876/assets?name=cli_1.0.213-rc4_linux_amd64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```
here it try to publish pr even though workflow is …

ci: set the relevant tag for goreleaser

---

cli/cmd/diagnose_util/logs_util.go

Since adding the deviceplugin container, we were not able to fetch odiglet logs since the container must be specified
```bash
container name must be specified for pod odiglet-rdzjz, choose one of: [init deviceplugin odiglet]
```

CORE-105 chore: specify the container once streaming logs

---

.github/workflows/e2e.yaml

chore: run e2e also on PR to releases/* branches

---

api/config/crd/bases/odigos.io_destinations.yaml
api/generated/odigos/applyconfiguration/odigos/v1alpha1/destinationspec.go
api/odigos/v1alpha1/destination_types.go
api/odigos/v1alpha1/zz_generated.deepcopy.go
autoscaler/controllers/clustercollector/configmap.go
docs/api-reference/odigos.io.v1alpha1.mdx
frontend/graph/generated.go
frontend/graph/model/models_gen.go
frontend/graph/schema.graphqls
frontend/graph/schema.resolvers.go
frontend/services/destinations.go
frontend/webapp/components/lib-imports/setup-header.tsx
frontend/webapp/graphql/mutations/destination.ts
frontend/webapp/graphql/queries/destination.ts
frontend/webapp/package.json
frontend/webapp/yarn.lock
helm/odigos/templates/crds/odigos.io_destinations.yaml

This PR allows the user to disable the destination without deleting the configuration.
The destination spec object now contains a `disabled` field, which controls whether or not these destinations should be filtered out by the `syncConfigMap` function for Odigos's routing system.
Overview
Drawer Read
Drawer Update
Overview
Drawer Read
Drawer Update

feat: disable destinations

---

api/k8sconsts/odiglet.go
cli/cmd/resources/odiglet.go
helm/odigos/templates/odiglet/daemonset.yaml
tests/common/assert/odigos-installed.yaml

If mount method is not `k8s-virtual-device` do not install device-plugin container

chore: in case mount-method is not used do not mount the deviceplugin + adjust grpc healthcheck CORE-125

---

profiles/aggregators/kratos.go
profiles/allprofiles.go
profiles/attributes/semconvdynamo.go
profiles/attributes/semconvredis.go
profiles/manifests/semconvdynamo.yaml
profiles/manifests/semconvredis.yaml

Downgrades `db.system.name` to `db.system` for DynamoDB following new instrumentation added in https://github.com/odigos-io/enterprise-go-instrumentation/pull/1560
It also sets `db.operation` to the value of `rpc.method` based on https://github.com/odigos-io/enterprise-go-instrumentation/pull/1560#discussion_r2260694632

RUN-92: Downgrade DynamoDB/Redis semconv attributes in Kratos profile

---

agents/python/setup.py

Had to bump python agent version, there I've set the wrapt version to avoid upgrade it during new odiglet deployments.

chore: set wrapt version - CORE-136

---

api/actions/v1alpha1/addclusterinfo_types.go
api/config/crd/bases/actions.odigos.io_addclusterinfos.yaml
api/config/crd/bases/odigos.io_actions.yaml
api/generated/actions/applyconfiguration/actions/v1alpha1/addclusterinfospec.go
autoscaler/controllers/actions/action_controller.go
autoscaler/controllers/actions/addclusterinfo_controller.go
docs/api-reference/actions.odigos.io.v1alpha1.mdx
helm/odigos/templates/crds/actions.odigos.io_addclusterinfos.yaml
helm/odigos/templates/crds/odigos.io_actions.yaml

Currently, we can only add new cluster info attributes since we hard code `insert` as the action in the resource processor. Allowing users to toggle to `upsert` gives the option to overwrite existing attributes.
A toggle was chosen for better UX, as the details of "insert" vs "upsert" may be overly technical (and users do have the option of manually creating a Processor CRD anyway).
Similarly, this option applies to the entire Action instead of individual attributes for simpler UX.

CORE-127: Add OverwriteExistingValues option to AddClusterInfo action

---

autoscaler/controllers/nodecollector/daemonset.go
autoscaler/controllers/nodecollector/sync.go
tests/common/assert/pipeline-ready.yaml

In order to minimize permissions for the node collector and minimize the `hostPath` volumes:
* only add the host mounts when required - either by logs or metrics destination. When only sending traces host mounts are not required.
* the node collector is only set to being a privileged container if either logs or metrics destination is present. If either of those signals is required we set the container to privileged - which is the current behavior. When only sending traces the collector is run not privileged.  This can be further refined in the future when we'll add more alternatives for collection host metrics or logs.
Tested with logs and metrics destination, verified the daemonset is reconciled correctly once this destination is added. Once that destination is removed and we are only …

fix: only add hostPath mounts and privelged to the data-collection when required by a metrics or logs destination

---

common/config/awss3.go
destinations/data/awss3.yaml
docs/backends/awss3.mdx
docs/mint.json

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37954 added a breaking change upstream where the old `s3_partition` field was removed in favor of `s3_parittion_format` which causes our collectors to crash with `'s3uploader' has invalid keys: s3_partition`.
For backward compatibility with our users, we must continue supporting the deprecated field and translating it to the new field. The old field is marked as deprecated.

PLAT-118: Support S3 partition format field

---

.github/workflows/promote-rc-to-stable.yml
.github/workflows/publish-modules.yml

Re-tag the rc images so it's fast, and to guarantee they are identical to what has been tested.
cli still need to be published as usual:
- cli is embedded with the version inside it (`odigos --version`)
- the cli goreleaser is the one creating the release in github
- new tag still needs helm version and openshift certification which the release-cli workflow does

ci: promote release-candidate to stable

---

.github/workflows/create-patch.yml
.github/workflows/create-release-candidate.yml
.github/workflows/openshift-preflight.yml
.github/workflows/promote-rc-to-stable.yml
.github/workflows/publish-modules.yml
.github/workflows/release.yml

Fixes: CORE-186
nit improvement to the CI release. it is currently clattered with many individual "curl"s to update slack for release notifications.
This logic is now extracted to https://github.com/odigos-io/github-actions where it's abstracted and reusable, and also guarantee consistent formating

ci: use the odigos slack-release-notification action for publish modules

---

autoscaler/controllers/clustercollector/deployment.go

Fixes: CORE-188
Our gateway collector, under load, will have it's CPU and memory under pressure. If the CPU is the limiting factor, then the endpoint for the health_check might take time to response, and can timeout the kubelet caller, and fail the check.
After 2 failed check the collector will be restarted.
This PR increase the value to 5 seconds (which is still an arbitrary number, but less likely to fail).

fix(collector): increase the livness probe to 5 sec

---

collector/config/configgrpc/configgrpc.go
collector/config/configgrpc/configgrpc_test.go

Fixes: CORE-194
Until now, we were using interceptors which runs after gRPC has already decoded the export request into memory.
This can dramatically increase the memory usage even when under memory pressure.
This PR move the memory pressure check to happen before the gRPC decode which increases the stability

fix: reject data in memory limit before grpc decode

---

tests-infrastructure/terraform/aks/main.tf

In aks we dont have enough resources to deploy odigos with the test apps
```
odigos-test   48s         Warning   FailedScheduling               pod/odigos-gateway-675b9dc8bb-9wpxs                    0/2 nodes are available: 1 Insufficient memory, 2 Insufficient cpu. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod.
```

chore: make aks cluster node a bit bigger - CORE-199

---

odiglet/pkg/ebpf/sdks/go.go

Since data collection and odiglet are now two containers in the same pod we can use localhost for them to communicate and by that solve reported issues about local services problems.

feat: odiglet will communicate with data collection using localhost - CORE-195

---

api/config/crd/bases/odigos.io_instrumentationconfigs.yaml
api/generated/odigos/applyconfiguration/odigos/v1alpha1/containeragentconfig.go
api/odigos/v1alpha1/instrumentationconfig_types.go
api/odigos/v1alpha1/zz_generated.deepcopy.go
common/env_injection_method.go
docs/api-reference/odigos.io.v1alpha1.mdx
helm/odigos/templates/crds/odigos.io_instrumentationconfigs.yaml
instrumentor/controllers/agentenabled/sync.go

Fixes: CORE-205
Just renaming the existing property, and introducing an enum for the decisions.
Using one enum for both config and decision was confusing, as the `loader-fallback-to-pod-manifest` does not feet well into this step which is what we are actually going to use

chore: introduce an enum for env injection decision and use in reconcile

---

api/k8sconsts/cli.go
api/k8sconsts/odiglet.go
cli/cmd/config.go
common/consts/consts.go
common/odigos_config.go
docs/cli/odigos_config.mdx
docs/instrumentations/golang/ebpf.mdx
docs/setup/docker-registry.mdx
helm/odigos/templates/odigos-configuration-cm.yaml
helm/odigos/values.yaml
scheduler/cmd/main.go
scheduler/controllers/odigosconfiguration/odigosconfiguration_controller.go
scheduler/controllers/odigospro/manager.go
scheduler/controllers/odigospro/offsets_controller.go

This enables users to set automatic updates using our published cli-offsets docker image rather than pulling directly from the hosted file in GCS. The user still needs Internet access to pull the image, but that access is now shifted from the cluster to their own registry/image mirror, which may work better for some disconnected environments.

CORE-173: Enable mirrored image automatic Go offsets updates

---

instrumentor/controllers/agentenabled/distroparams.go
instrumentor/controllers/agentenabled/pods_webhook.go
instrumentor/controllers/agentenabled/sync.go

Fixes: CORE-160
Distro params are a way to propagate parameters from the runtime detection into the webhook, to be used during the injection of the distro in the webhook.
It allows use to:
- verify the value from runtime detection is available when required
- the value is in the right format (for example - a version number)
- process the value to make it useful for the webhook (for example, calculate MAJOR.MINOR for ruby/php)
- simplify the code in webhook (get processed values without needing to validate or compute anything)
- transaction - the values are all coming from the reconcile, so if the runtime details are updated, there will be no race with the new result of the reconcile and the webhook that also access these values.
This PR extract the functions to handle the distro params to …

chore: refactor distro params handling

---

api/k8sconsts/clustercollector.go
api/odigos/v1alpha1/destination_types.go
autoscaler/controllers/clustercollector/configmap.go
autoscaler/controllers/clustercollector/deployment.go
autoscaler/controllers/clustercollector/destination_controller_test.go
autoscaler/controllers/clustercollector/suite_test.go
autoscaler/controllers/clustercollector/sync.go
autoscaler/k8sconfig/config.go
autoscaler/k8sconfig/gcp.go
autoscaler/k8sconfig/root.go
common/config/gcp.go
destinations/data/googlecloudmonitoring.yaml
docs/adding-new-dest.mdx
docs/backends/googlecloudmonitoring.mdx
frontend/services/destinations.go

This adds the following options to the GCP exporter:
* `timeout` -- configure timeout for requests to cloud observability API
* `project ID` -- used when sending telemetry to a different GCP project than where the app is currently running (also conditionally required if running off-GKE and sending traces to GCP observability)
* `billing project ID` -- the *billing* project for counting trace quota usage when sending to GCP
* `Google application credentials` -- service account token/info for sending traces to GCP when running off GKE
Application credentials requires something new where a Destination can conditionally configure the Collector Deployment. This is because, when setting custom credentials for GCP, the exporter needs the credentials as a file in the Pod.
This is implemented with …

CORE-134: Add more options for GCP exporter + K8sConfiger interface

---

cli/cmd/resources/autoscaler.go
helm/odigos/templates/autoscaler/role.yaml

Adding permissions for the autoscaler to update actions to the generic CRD
Deployed locally with helm, made sure we don't get the permissions error anymore and that the actions are visible in the UI again

CORE-269 adding create role for service account (#3527)

---

profiles/aggregators/kratos.go

Fixes: CORE-271
since the upstream grpc max payload size in increased long ago, the small batches are no longer needed and will improve cpu and memory consumption.
The profile itself is not removed and can be introduced via the profiles

chore: remove small batches from kratos profile

---

autoscaler/controllers/nodecollector/collectorconfig/spanmetrics.go

Fixes: CORE-271
`status.code` is included in `exclude_dimensions` but it is needed.
not sure why it was there to begin with - probably copied from the example from the connector README

fix: do not exclude status code from dimensions

---

.github/workflows/promote-rc-to-stable.yml

Promote enterprise images to all registries (Docker Hub, GHCR, GCR) alongside open-source images per customer request.

chore: publish all enterprise images include tower to all registries - DEVOPS-26
